### ISSUE TITLE
`java.lang.NoClassDefFoundError: com/clickhouse/client/http/HttpClientConnectionImpl

### ISSUE THREAD

**Issue by kiwimg** [ClickHouse/clickhouse-java#1002]
0.3.1 update to  v0.3.2-patch10
java  11
`  
<dependency>
                <groupId>com.clickhouse</groupId>
                <artifactId>clickhouse-jdbc</artifactId>
                <version>0.3.2-patch10</version>
                <classifier>all</classifier>
                <exclusions>
                    <exclusion>
                        <groupId>*</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
`

`java.lang.NoClassDefFoundError: com/clickhouse/client/http/HttpClientConnectionImpl
	at com.clickhouse.client.http.ClickHouseHttpClient.newConnection(ClickHouseHttpClient.java:53) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.client.http.ClickHouseHttpClient.newConnection(ClickHouseHttpClient.java:23) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.client.AbstractClient.getConnection(AbstractClient.java:193) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:87) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:296) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:191) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:202) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:234) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1748) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:79) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:244) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:214) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:145) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:41) ~[clickhouse-jdbc-0.3.2-patch10-all.jar!/:clickhouse-jdbc 0.3.2-patch10 (revision: aebad16)]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1643) ~[druid-1.2.11.jar!/:1.2.11]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1709) ~[druid-1.2.11.jar!/:1.2.11]`

**Comment by zhicwu** [comment]
The dependency looks good but not sure why ended up with class not found exception. Did you resolve this?

**Comment by kiwimg** [comment]
没有解决 、之后完全复制version 11 下面的class 到自己工程中

**Comment by kiwimg** [comment]
This should be a bug

**Comment by hhoughgg** [comment]
I have the same issue using this driver with Spark. I tried using the -all tag as suggested in another issue which did not help. Using the same patch10 version.

**Comment by kiwimg** [comment]
This problem is still not solved,0.3.2_batch11

java -version
java version "11.0.6" 2020-01-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.6+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.6+8-LTS, mixed mode, sharing)`

**Comment by zhicwu** [comment]
> This problem is still not solved,0.3.2_batch11

Sorry to hear about that. Just tried `../ClickHouse/clickhouse-jdbc/tree/master/examples/jdbc` without any issue. Could you provide minimum reproducible code?

**Comment by kiwimg** [comment]
My program runs on docker

**Comment by mlkui** [comment]
Same issue with SpringBoot when running 'maven package' output jar.

**Comment by Donxiaohao** [comment]
How to due this question? 
 i use 0.6.0 verison happened。
However, it runs normally locally, and when packaged to the server, an error message appears.
[ClickHouseWorker-2] DEBUG c.clickhouse.client.ClickHouseClientBuilder$Agent - Handling java.lang.NoClassDefFoundError: com/clickhouse/client/http/HttpClientConnectionImpl(failover=0，retry=0)
@zhicwu
