### ISSUE TITLE
Cannot accept String as JSON value

### ISSUE THREAD

**Issue by pirosveta** [ClickHouse/clickhouse-java#1191]
Observed:
Calling PreparedStatement.setString for a column of type JSON with a String as parameter throws exception:

```
java.lang.NumberFormatException: For input string: "{}"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[na:na]
	at java.base/java.lang.Integer.parseInt(Integer.java:668) ~[na:na]
	at java.base/java.lang.Short.parseShort(Short.java:137) ~[na:na]
	at java.base/java.lang.Short.parseShort(Short.java:163) ~[na:na]
	at com.clickhouse.client.data.ClickHouseShortValue.update(ClickHouseShortValue.java:243) ~[clickhouse-cli-client-0.3.2-patch11-shaded.jar:clickhouse-cli-client 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.client.data.ClickHouseShortValue.update(ClickHouseShortValue.java:14) ~[clickhouse-cli-client-0.3.2-patch11-shaded.jar:clickhouse-cli-client 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.client.ClickHouseValue.update(ClickHouseValue.java:1270) ~[clickhouse-cli-client-0.3.2-patch11-shaded.jar:clickhouse-cli-client 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.client.data.ClickHouseShortValue.update(ClickHouseShortValue.java:259) ~[clickhouse-cli-client-0.3.2-patch11-shaded.jar:clickhouse-cli-client 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.client.data.ClickHouseShortValue.update(ClickHouseShortValue.java:14) ~[clickhouse-cli-client-0.3.2-patch11-shaded.jar:clickhouse-cli-client 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.lambda$buildMappingsForDataTypes$84(ClickHouseRowBinaryProcessor.java:435) ~[clickhouse-cli-client-0.3.2-patch11-shaded.jar:clickhouse-cli-client 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.serialize(ClickHouseRowBinaryProcessor.java:486) ~[clickhouse-cli-client-0.3.2-patch11-shaded.jar:clickhouse-cli-client 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:333) ~[clickhouse-jdbc-0.3.2-patch11.jar:clickhouse-jdbc 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeAny(InputBasedPreparedStatement.java:110) ~[clickhouse-jdbc-0.3.2-patch11.jar:clickhouse-jdbc 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeQuery(InputBasedPreparedStatement.java:161) ~[clickhouse-jdbc-0.3.2-patch11.jar:clickhouse-jdbc 0.3.2-patch11 (revision: 27f8951)]
```
Version: 0.3.2-patch11

Expected:
The client is able to accept a string as value for JSON.

**Comment by zhicwu** [comment]
Please bump driver to v0.4.6 or above, and use `input` function as mentioned in #1023 for inserting JSON as string.
