### ISSUE TITLE
Use clickhouse-jdbc save bitmap to CK error 

### ISSUE THREAD

**Issue by yanye666** [ClickHouse/clickhouse-java#1215]
### version
jdbc-0.3.2-patch11
clickhouse 21.7

### DDL
create table table
(
    result_bit AggregateFunction(groupBitmap, UInt32)
);

###  Insert Code
insert into table(member_label_id)
        values (1, 1, now(), #{bitMap}, 1, 1);
#### 

Use mybatis BaseTypeHandler
    @Override
    public void setNonNullParameter(PreparedStatement ps, int i, RoaringBitmap parameter, JdbcType jdbcType) throws SQLException {
        ps.setObject(i, ClickHouseBitmap.wrap(parameter, ClickHouseDataType.UInt32));
    }       

### stack
Caused by: java.sql.SQLException: Code: 62. DB::Exception: Cannot parse expression of type AggregateFunction(groupBitmap, UInt32) here: com.clickhouse.client.data.ClickHouseBitmap$ClickHouseRoaringBitmap@4f1dd190, 1, 1): While executing ValuesBlockInputFormat. (SYNTAX_ERROR) (version 21.9.7.2 (official build))
, server ClickHouseNode [uri=http://192.168.60.43:8123/sales_db_dev]@543661838
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeStatement(ClickHouseStatementImpl.java:162)
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeAny(SqlBasedPreparedStatement.java:150)
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.execute(SqlBasedPreparedStatement.java:419)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:427)
	... 40 more

**Comment by zhicwu** [comment]
Hi @yanye666, it's usually a bad sign when you see SqlBasedPreparedStatement in the stack trace. It means the JDBC driver was trying to substitute parameters in the given query in string format, which is slow and most importantly not type-safe. Could you try `input` function as shown in examples for the insertion?

**Comment by yanye666** [comment]
> 你好@yanye666，当您在堆栈跟踪中看到 SqlBasedPreparedStatement 时，通常是一个不好的迹象。这意味着 JDBC 驱动程序试图以字符串格式替换给定查询中的参数，这很慢而且最重要的是类型不安全。您可以尝试`input`插入示例中所示的功能吗？

input is ok

**Comment by yanye666** [comment]
#874 Reference to this content to change the sql, can be realized

**Comment by XuanGX** [comment]
> > 你好@yanye666，当您在堆栈跟踪中看到 SqlBasedPreparedStatement 时，通常是一个不好的迹象。这意味着 JDBC 驱动程序试图以字符串格式替换给定查询中的参数，这很慢而且最重要的是类型不安全。您可以尝试`input`插入示例中所示的功能吗？
> 
> input is ok

Hello, I'm having the same problem. Can mybatis use the input function?

**Comment by yanye666** [comment]
> #874 Reference to this content to change the sql, can be realized

https://github.com/ClickHouse/clickhouse-java/issues/874 Reference to this content to change the sql, can be realized

**Comment by yanye666** [comment]
> > > 你好@yanye666，当您在堆栈跟踪中看到 SqlBasedPreparedStatement 时，通常是一个不好的迹象。这意味着 JDBC 驱动程序试图以字符串格式替换给定查询中的参数，这很慢而且最重要的是类型不安全。您可以尝试`input`插入示例中所示的功能吗？
> > 
> > 
> > input is ok
> 
> Hello, I'm having the same problem. Can mybatis use the input function?

https://github.com/ClickHouse/clickhouse-java/issues/874 Reference to this content to change the sql, can be realized
