### ISSUE TITLE
Fail to insert VARBINARY type using clickhouse-jdbc with new driver com.clickhouse.jdbc.ClickHouseDriver

### ISSUE THREAD

**Issue by luoyuxia** [ClickHouse/clickhouse-java#1244]
I use clickhouse jdbc 0.3.2 and the new driver com.clickhouse.jdbc.ClickHouseDriver, but encounter an exception when inserting binary data into clickhouse. 
It can be reproduced with the following code:
```java
private static final String DRIVER_NAME = "com.clickhouse.jdbc.ClickHouseDriver"
public static void main(String[] args) throws Exception {
        Properties info = new Properties();
        info.setProperty("user", CLICKHOUSE_USERNAME);
        info.setProperty("password", CLICKHOUSE_PASSWORD);
        Driver loadedDriver = loadDriver(DRIVER_NAME);

        try (Connection connection = loadedDriver.connect(CLICKHOUSE_JDBC_URL, info)) {
            Statement statement = connection.createStatement();
            String createTableDDL =
                    "create table if not exists t1(id int, varbinary_data VARBINARY) ENGINE = MergeTree() ORDER By id";
            statement.execute(createTableDDL);
            int i = 1;
            byte[] bytes = "charlie".getBytes();
            PreparedStatement preStatement =
                    connection.prepareStatement(
                            "INSERT INTO `t1`(`id`, `varbinary_data`) VALUES (?, ?)");
            preStatement.setInt(1, i);
            preStatement.setBytes(2, bytes);
            preStatement.execute();
        }
    }

private static Driver loadDriver(String driverName)
            throws SQLException, ClassNotFoundException {
        Preconditions.checkNotNull(driverName);
        Enumeration<Driver> drivers = DriverManager.getDrivers();
        while (drivers.hasMoreElements()) {
            Driver driver = drivers.nextElement();
            if (driver.getClass().getName().equals(driverName)) {
                return driver;
            }
        }
        // We could reach here for reasons:
        // * Class loader hell of DriverManager(see JDK-8146872).
        // * driver is not installed as a service provider.
        Class<?> clazz =
                Class.forName(driverName, true, Thread.currentThread().getContextClassLoader());
        try {
            return (Driver) clazz.newInstance();
        } catch (Exception ex) {
            throw new SQLException("Fail to create driver of class " + driverName, ex);
        }
    }
```
It'll then throw 
```java
Exception in thread "main" java.sql.SQLException: Code: 47. DB::Exception: Missing columns: 'charlie' while processing query: 'charlie', required columns: 'charlie' 'charlie': While executing ValuesBlockInputFormat. (UNKNOWN_IDENTIFIER) (version 22.3.3.2)
, server ClickHouseNode(addr=xxxx, db=default)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:54)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:69)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeStatement(ClickHouseStatementImpl.java:139)
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeBatch(SqlBasedPreparedStatement.java:128)
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.execute(SqlBasedPreparedStatement.java:382)
	at org.apache.flink.connector.clickhouse.T3.main(T3.java:61)
Caused by: java.io.IOException: Code: 47. DB::Exception: Missing columns: 'charlie' while processing query: 'charlie', required columns: 'charlie' 'charlie': While executing ValuesBlockInputFormat. (UNKNOWN_IDENTIFIER) (version 22.3.3.2)

	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:130)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:201)
	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:88)
	at com.clickhouse.client.http.ClickHouseHttpClient.execute(ClickHouseHttpClient.java:115)
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1375)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeStatement(ClickHouseStatementImpl.java:133)
	... 3 more
```
But when I changed the `DRIVER_NAME` to `ru.yandex.clickhouse.ClickHouseDriver`, it works well

**Comment by zhicwu** [comment]
Thanks for the report @luoyuxia. Will take a look when I get home. Meanwhile, could you try v0.3.2-patch11(Maven groupId is `com.clickhouse`)? Alternatively, you may try v0.4.0 with connection property `use_binary_string` set to `true`?

FYI, starting from v0.4.0, the driver treats `String` as text by default, but you may enable binary support by setting `use_binary_string` to `true`, at the cost of additional memory footprints(due to unnecessary byte array copy) and ~10% performance degrade when handling String.

**Comment by luoyuxia** [comment]
@zhicwu Thanks for quick response. 0.3.2-patch11 works well.
But I'm curious about why 0.3.2-patch11 works, is there any issue/pr fix it?

**Comment by zhicwu** [comment]
> @zhicwu Thanks for quick response. 0.3.2-patch11 works well. 

Good to know.

> But I'm curious about why 0.3.2-patch11 works, is there any issue/pr fix it?

It was an issue before v0.3.2-patch3. PR #815 fixed the issue and passed regression test in trino.
