### ISSUE TITLE
JDBC driver cannot be connected properly

### ISSUE THREAD

**Issue by joson1205** [ClickHouse/clickhouse-java#1253]
CH Version: 21.4.6.55
Can not be used normally, I do not know whether there is a mistake in my way of use.

```text
15:54:30.103 [main] DEBUG com.clickhouse.jdbc.ClickHouseDriver - ClickHouse Driver 0.4.1.0(JDBC: 4.2.0.0) registered
15:54:30.213 [main] DEBUG com.clickhouse.client.ClickHouseNodeSelector - Checking [com.clickhouse.client.cli.ClickHouseCommandLineClient@71e7a66b] against [HTTP]...
15:54:30.214 [main] DEBUG com.clickhouse.client.ClickHouseNodeSelector - Checking [com.clickhouse.client.grpc.ClickHouseGrpcClient@1c53fd30] against [HTTP]...
15:54:30.215 [main] DEBUG com.clickhouse.client.ClickHouseNodeSelector - Checking [com.clickhouse.client.http.ClickHouseHttpClient@50cbc42f] against [HTTP]...
15:54:30.218 [main] DEBUG com.clickhouse.jdbc.internal.ClickHouseConnectionImpl - Connecting to: ClickHouseNode [uri=http://xx.xx.xx.xx:8123/default]@-1434768565
15:54:30.219 [main] DEBUG com.clickhouse.client.AbstractClient - Connecting to: ClickHouseNode [uri=http://xx.xx.xx.xx:8123/default]@-1434768565
15:54:30.227 [main] DEBUG com.clickhouse.client.AbstractClient - Connection established: com.clickhouse.client.http.HttpUrlConnectionImpl@7cdbc5d3
15:54:30.227 [main] DEBUG com.clickhouse.client.http.ClickHouseHttpClient - Query: select currentUser() user, timezone() timezone, version() version, toUInt8(ifnull((select value from system.settings where name = 'readonly'), '0')) as readonly, toInt8(ifnull((select value from system.settings where name = 'throw_on_unsupported_query_inside_transaction'), '-1')) as throw_on_unsupported_query_inside_transaction, lower(ifnull((select value from system.settings where name = 'wait_changes_become_visible_after_commit_mode'), '')) as wait_changes_become_visible_after_commit_mode,toInt8(ifnull((select value from system.settings where name = 'implicit_transaction'), '-1')) as implicit_transaction, toUInt64(ifnull((select value from system.settings where name = 'max_insert_block_size'), '0')) as max_insert_block_size, toInt8(ifnull((select value from system.settings where name = 'allow_experimental_lightweight_delete'), '-1')) as allow_experimental_lightweight_delete FORMAT RowBinaryWithNamesAndTypes
15:54:30.540 [main] DEBUG com.clickhouse.client.ClickHouseClientBuilder$Agent - Handling com.clickhouse.client.ClickHouseException: Connection reset, server ClickHouseNode [uri=http://xx.xx.xx.xx:8123/default]@-1434768565(failover=0, retry=0)
Exception in thread "main" java.sql.SQLException: Connection reset, server ClickHouseNode [uri=http://xx.xx.xx.xx:8123/default]@-1434768565
       at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
       at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
       at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
       at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:124)
       at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:333)
       at com.clickhouse.jdbc.ClickHouseDataSource.getConnection(ClickHouseDataSource.java:46)
       at ClickhouseJDBC.main(ClickhouseJDBC.java:19)
Caused by: java.net.SocketException: Connection reset
       at java.net.SocketInputStream.read(SocketInputStream.java:210)
       at java.net.SocketInputStream.read(SocketInputStream.java:141)
       at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
       at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
       at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
       at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
       at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
       at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
       at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
       at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:154)
       at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:227)
       at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:124)
       at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:298)
       at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282)
       at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294)
       at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349)
       at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:1025)
       at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2074)
       at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:121)
       ... 3 more
```

```pom.xml
  <dependency>
      <groupId>com.clickhouse</groupId>
      <artifactId>clickhouse-jdbc</artifactId>
      <version>0.4.1</version>
      <classifier>all</classifier>
  </dependency>
```
Demo code:
```java
  public static void main(String[] args) throws SQLException {
      String url = "jdbc:ch://xx.xx.xx.xx:8123";
      Properties properties = new Properties();
      properties.setProperty("user", "user");
      properties.setProperty("password", "pwd");
      ClickHouseDataSource dataSource = new ClickHouseDataSource(url, properties);
      try (Connection conn = dataSource.getConnection();
           Statement stmt = conn.createStatement();
           ResultSet rs = stmt.executeQuery("show databases")) {
      }
  }
```

**Comment by zhicwu** [comment]
Is the server up and running? Can you try again by changing url to `jdbc:ch:https://explorer@play.clickhouse.com:443` and removing user and password properties?

**Comment by joson1205** [comment]
> 

I quoted a different version. It works!!
```pom.xml
      <dependency>
          <groupId>ru.yandex.clickhouse</groupId>
          <artifactId>clickhouse-jdbc</artifactId>
          <version>0.3.2</version>
      </dependency>
```
Errors are reported only when using the advanced version.
changing url to ` jdbc:ch:https://explorer@play.clickhouse.com:443` and removing user and password properties, is also effective.But I can make sure that my database service is working.

**Comment by zhicwu** [comment]
> changing url to  jdbc:ch:https://explorer@play.clickhouse.com:443 and removing user and password properties, is also effective

Any proxy between the server and jdbc client?

**Comment by zhicwu** [comment]
I think you can also change url to `jdbc:ch://xx.xx.xx.xx:8123?use_no_proxy` and see how it goes.

**Comment by joson1205** [comment]
> I think you can also change url to `jdbc:ch://xx.xx.xx.xx:8123?use_no_proxy` and see how it goes.

I see, thanks for your kind interpretation.
