### ISSUE TITLE
Nested value can only be inserted if number of rows matches number of columns

### ISSUE THREAD

**Issue by C0mbatwombat** [ClickHouse/clickhouse-java#1259]
### Steps to reproduce
1. Applying this patch and running mvn test in clickhouse-data shows the error: 
```Index: clickhouse-data/src/test/java/com/clickhouse/data/value/ClickHouseNestedValueTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/clickhouse-data/src/test/java/com/clickhouse/data/value/ClickHouseNestedValueTest.java b/clickhouse-data/src/test/java/com/clickhouse/data/value/ClickHouseNestedValueTest.java
--- a/clickhouse-data/src/test/java/com/clickhouse/data/value/ClickHouseNestedValueTest.java	(revision 032f7362f24ad5262bbbb7793391da5f70ee302e)
+++ b/clickhouse-data/src/test/java/com/clickhouse/data/value/ClickHouseNestedValueTest.java	(date 1677577717681)
@@ -51,8 +51,8 @@
         // mixed types
         checkValue(
                 ClickHouseNestedValue.of(ClickHouseColumn.parse("a Nullable(UInt8), b Date"),
-                        new Object[][] { new Short[] { (short) 1, null },
-                                new LocalDate[] { LocalDate.ofEpochDay(1L), LocalDate.ofEpochDay(2L) } }),
+                        new Object[][] { new Short[] { (short) 1, null, (short) 2 },
+                                new LocalDate[] { LocalDate.ofEpochDay(1L), LocalDate.ofEpochDay(2L), LocalDate.ofEpochDay(3L) } }),
                 UnsupportedOperationException.class, // isInfinity
                 UnsupportedOperationException.class, // isNan
                 false, // isNull
```
```
[ERROR] Tests run: 1563, Failures: 1, Errors: 0, Skipped: 113, Time elapsed: 24.073 s <<< FAILURE! - in TestSuite
[ERROR] com.clickhouse.data.value.ClickHouseNestedValueTest.testMultipleValues  Time elapsed: 0.005 s  <<< FAILURE!
java.lang.IllegalArgumentException: Columns and values should have same length
        at com.clickhouse.data.value.ClickHouseNestedValue.check(ClickHouseNestedValue.java:74)
        at com.clickhouse.data.value.ClickHouseNestedValue.<init>(ClickHouseNestedValue.java:84)
```

### Expected behaviour
Inserting 3 rows into a nested field with 2 columns should be allowed

#### Environment
* Client version: 4.1.0

**Comment by zhicwu** [comment]
Hi @C0mbatwombat, thanks for the report. What was the specific issue you ran into? Did you encounter error when deserializing `Nested` or `JSON` value?

Anyway, it's a 2-dimensional row-to-column array, so the check method is just to ensure the inner array's length is same as column count. Actually you may verify that by using below example:
```sql
set allow_experimental_object_type = 1;
drop table if exists json3;
CREATE TABLE json3
(
    o JSON
) ENGINE = Memory;
truncate table json3;
insert into json3 (o) values ('{"a": [{"b1":1,"b2":1,"b3":1},{"b1":2,"b2":2,"b3":2},{"b1":3,"b2":3,"b3":3},{"b1":4,"b2":4,"b3":4}]}');
select o, toTypeName(o) t from json3;

o	t
[[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]]	Tuple(a Nested(b1 Int8, b2 Int8, b3 Int8))
```

Having said that, we may drop the check method in the future if there's performance concern.

**Comment by C0mbatwombat** [comment]
Hi @zhicwu, thanks for the quick reply. I ran into the problem when using a Nested value. The reported bug was not present pre-0.4.1, ie. the system was working in 0.4.0.
In 0.4.0, I would pass a values array with dimensions: `values[numColumns][numRows]` to the constructor `ClickHouseNestedValue.of(clickhouseColumns, values))` , however now that results in `IllegalArgumentException("Columns and values should have same length")` (ClickhouseNestedValue:73).

I think the assumption how the nested value should be provided has changed from 0.4.0 to 0.4.1, and this has not been picked up by the tests as most/all tests expect 2 rows and 2 columns.

**Comment by C0mbatwombat** [comment]
FYI I use the jdbc driver to set the nested field: `ps.setObject(idx, ClickHouseNestedValue.of(clickhouseColumns, values));`

**Comment by C0mbatwombat** [comment]
Thanks!

**Comment by C0mbatwombat** [comment]
Thanks for the change, I got it work after looking at the test cases and not using the input() function anymore. 
This now works:
```
s.execute("set flatten_nested=0;" + "drop table if exists test_nested_insert;"
        + "create table test_nested_insert(id UInt32, n Nested(c1 Int8, c2 LowCardinality(String)))engine=Memory");
try (PreparedStatement ps = conn.prepareStatement("insert into test_nested_insert(id, n)")) {
    ps.setString(1, "3");
    ps.setObject(2,
            ClickHouseNestedValue.of(
                    ClickHouseColumn.of("n", "Nested(c1 Int8, c2 LowCardinality(String))").getNestedColumns(),
                    new Object[][] { { 1, "foo" }, { 2, "bar" }, { 3, "bug" } }));
    ps.executeUpdate();
}
```

But I couldn't get it to work using an input function as recommended. I tried the following: 
```
try (PreparedStatement ps = conn.prepareStatement("insert into test_nested_insert(id, n) select id, n from input('id UInt32, n Nested(c1 Int8, c2 LowCardinality(String)))'")) {
    ps.setString(1, "3");
    ps.setObject(2,
            ClickHouseNestedValue.of(
                    ClickHouseColumn.of("n", "Nested(c1 Int8, c2 LowCardinality(String))").getNestedColumns(),
                    new Object[][] { { 1, "foo" }, { 2, "bar" }, { 3, "bug" } }));
    ps.executeUpdate();
}
```
which results in 
```
Caused by: java.lang.IllegalArgumentException: At least one SQL statement is required for execution
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:96)
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349)
	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:1056)
	at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeInsert(ClickHouseStatementImpl.java:316)
	... 5 common frames omitted
```

Splitting the insert up in columns doesn't work anymore because of the changed input format. This:
```
try (PreparedStatement ps = conn.prepareStatement("insert into test_nested_insert(id, n.c1, n.c2) select id, n.c1, n.c2 from input('id UInt32, n Nested(c1 Int8, c2 LowCardinality(String)))'")) {
    ps.setString(1, "3");
    ps.setObject(2, new Object[] { 1, 2, 3});
    ps.setObject(3, new Object[] { "foo", "bar", "bug"});
    ps.executeUpdate();
}
```
results in this error: 
```
java.lang.IllegalArgumentException: Columns and values should have same length
	at com.clickhouse.data.value.ClickHouseNestedValue.check(ClickHouseNestedValue.java:74)
	at com.clickhouse.data.value.ClickHouseNestedValue.set(ClickHouseNestedValue.java:104)
	at com.clickhouse.data.value.ClickHouseNestedValue.update(ClickHouseNestedValue.java:572)
	at com.clickhouse.data.value.ClickHouseNestedValue.update(ClickHouseNestedValue.java:28)
	at com.clickhouse.data.ClickHouseValue.update(ClickHouseValue.java:1232)
```

Is there a way to use the input() function with nested columns? In the meantime I will rewrite our code to use the working approach without the input function.

**Comment by zhicwu** [comment]
Hi @C0mbatwombat, sorry for late reply. Couple of comments:
1. JDBC driver threw confusing error message when the query was invalid - will raise a PR to fix that
  ```sql
  -- original query
  insert into test_nested_insert(id, n) select id, n from input('id UInt32, n Nested(c1 Int8, c2 LowCardinality(String)))'
  -- should be changed to
  insert into test_nested_insert(id, n) select id, n from input('id UInt32, n Nested(c1 Int8, c2 LowCardinality(String))'
  ```
2. The difference between `insert into table` and `insert into table select * from input('...')` now is just an additional query `select * from table where 0` to get column types, which is usually fast, so you don't have to use input function all the time
3. ClickHouse*Value could be slow and consume more memory, so you probably don't want to use that. However, it can be used as a workaround to instruct JDBC driver to use strongly typed value(e.g. use DateTime64(7) instead of DateTime64)
4. Personally, I use Array and Tuple but never Nested and JSON on PROD - issue like ClickHouse/ClickHouse#49401 is scary

Working examples for your reference:
```java
s.execute("set flatten_nested=0; drop table if exists test_nested_insert; "
        + "create table test_nested_insert(id UInt32, n Nested(c1 Int8, c2 LowCardinality(String)))engine=Memory");
try (PreparedStatement ps = conn.prepareStatement("insert into test_nested_insert(id, n)")) {
    ps.setString(1, "1");
    ps.setObject(2, new Object[][] { { 1, "foo1" }, { 2, "bar1" }, { 3, "bug1" } });
    ps.executeUpdate();
}
// now use input function
try (PreparedStatement ps = conn.prepareStatement(
        "insert into test_nested_insert(id, n) select id, n from input('id UInt32, n Nested(c1 Int8, c2 LowCardinality(String))') settings flatten_nested=0")) {
    ps.setString(1, "2");
    ps.setObject(2, new Object[][] { { 4, "foo2" }, { 5, "bar2" }, { 6, "bug2" } });
    ps.executeUpdate();
}
try (ResultSet rs = s.executeQuery("select * from test_nested_insert order by id")) {
    for (int i = 1; i <= 2; i++) {
        Assert.assertTrue(rs.next());
        Assert.assertEquals(rs.getInt(1), i);
        Object[][] nestedValue = (Object[][]) rs.getObject(2);
        Assert.assertEquals(nestedValue.length, 3);
        String[] arr = new String[] { "foo", "bar", "bug" };
        for (int j = 1; j <= 3; j++) {
            Assert.assertEquals(nestedValue[j - 1],
                    new Object[] { (byte) (j + (i - 1) * 3), arr[j - 1] + i });
        }
    }
    Assert.assertFalse(rs.next());
}

s.execute("set flatten_nested=1; drop table if exists test_nested_insert; "
        + "create table test_nested_insert(id UInt32, n Nested(c1 Int8, c2 LowCardinality(String)))engine=Memory");
try (PreparedStatement ps = conn.prepareStatement(
        "insert into test_nested_insert(id, n.c1, n.c2) select id, c1, c2 from input('id UInt32, c1 Array(Int8), c2 Array(LowCardinality(String))')")) {
    ps.setString(1, "3");
    ps.setObject(2, new byte[] { 7, 8, 9 });
    ps.setObject(3, new String[] { "foo3", "bar3", "bug3" });
    ps.executeUpdate();
}
try (ResultSet rs = s.executeQuery("select * from test_nested_insert order by id")) {
    Assert.assertTrue(rs.next());
    Assert.assertEquals(rs.getInt(1), 3);
    Assert.assertEquals(rs.getObject(2), new byte[] { 7, 8, 9 });
    Assert.assertEquals(rs.getObject(3), new String[] { "foo3", "bar3", "bug3" });
    Assert.assertFalse(rs.next());
}
```
