### ISSUE TITLE
Parallel inserts cause increased latency

### ISSUE THREAD

**Issue by rrsunhome** [ClickHouse/clickhouse-java#1277]
Hi, I'm using the latest client version to test the performance of bulk inserts. When using multi-threaded insertion, it is found that the response time becomes longer and most threads hang

The test conditions are as follows:
Batch size: 50000 records
Number of threads: 10
```
"pool-2-thread-8" #21 prio=5 os_prio=31 tid=0x00007fea6d018800 nid=0x9903 runnable [0x000070000fe50000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	- locked <0x000000077ac78e48> (a java.io.BufferedOutputStream)
	at java.io.PrintStream.write(PrintStream.java:480)
	- locked <0x000000077ac78e60> (a java.io.PrintStream)
	at sun.net.www.http.ChunkedOutputStream.flush(ChunkedOutputStream.java:145)
	at sun.net.www.http.ChunkedOutputStream.write(ChunkedOutputStream.java:237)
	- locked <0x000000077ac78e80> (a sun.net.www.http.ChunkedOutputStream)
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3586)
	at com.clickhouse.client.stream.WrappedOutputStream.flushBuffer(WrappedOutputStream.java:19)
	at com.clickhouse.client.stream.AbstractByteArrayOutputStream.transferBytes(AbstractByteArrayOutputStream.java:43)
	at com.clickhouse.client.stream.AbstractByteBufferInputStream.pipe(AbstractByteBufferInputStream.java:90)
	at com.clickhouse.client.ClickHouseInputStream.pipe(ClickHouseInputStream.java:424)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:284)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:123)
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:296)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:284)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:296)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:351)
	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:824)
	at com.clickhouse.client.ClickHouseRequest$Mutation.executeAndWait(ClickHouseRequest.java:288)
	at com.clickhouse.client.ClickHouseRequest$Mutation.sendAndWait(ClickHouseRequest.java:314)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeInsert(ClickHouseStatementImpl.java:177)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeAny(InputBasedPreparedStatement.java:117)
	at com.clickhouse.jdbc.internal.AbstractPreparedStatement.executeLargeBatch(AbstractPreparedStatement.java:85)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:568)

"pool-2-thread-9" #22 prio=5 os_prio=31 tid=0x00007fea6d019000 nid=0x9703 runnable [0x000070000ff53000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	- locked <0x000000077ac5fd80> (a java.io.BufferedOutputStream)
	at java.io.PrintStream.write(PrintStream.java:480)
	- locked <0x000000077ac5fd98> (a java.io.PrintStream)
	at sun.net.www.http.ChunkedOutputStream.flush(ChunkedOutputStream.java:145)
	at sun.net.www.http.ChunkedOutputStream.write(ChunkedOutputStream.java:237)
	- locked <0x00000007722a8110> (a sun.net.www.http.ChunkedOutputStream)
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3586)
	at com.clickhouse.client.stream.WrappedOutputStream.flushBuffer(WrappedOutputStream.java:19)
	at com.clickhouse.client.stream.AbstractByteArrayOutputStream.transferBytes(AbstractByteArrayOutputStream.java:43)
	at com.clickhouse.client.stream.AbstractByteBufferInputStream.pipe(AbstractByteBufferInputStream.java:90)
	at com.clickhouse.client.ClickHouseInputStream.pipe(ClickHouseInputStream.java:424)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:284)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:123)
```

**Comment by rrsunhome** [comment]
> 您好，我正在使用最新的客户端版本来测试批量插入的性能。使用多线程插入时，发现响应时间变长，大部分线程挂掉
> 
> 测试条件如下： 批量大小：50000条记录 线程数：10
> 
> ```
> "pool-2-thread-8" #21 prio=5 os_prio=31 tid=0x00007fea6d018800 nid=0x9903 runnable [0x000070000fe50000]
>    java.lang.Thread.State: RUNNABLE
> 	at java.net.SocketOutputStream.socketWrite0(Native Method)
> 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
> 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
> 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
> 	- locked <0x000000077ac78e48> (a java.io.BufferedOutputStream)
> 	at java.io.PrintStream.write(PrintStream.java:480)
> 	- locked <0x000000077ac78e60> (a java.io.PrintStream)
> 	at sun.net.www.http.ChunkedOutputStream.flush(ChunkedOutputStream.java:145)
> 	at sun.net.www.http.ChunkedOutputStream.write(ChunkedOutputStream.java:237)
> 	- locked <0x000000077ac78e80> (a sun.net.www.http.ChunkedOutputStream)
> 	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3586)
> 	at com.clickhouse.client.stream.WrappedOutputStream.flushBuffer(WrappedOutputStream.java:19)
> 	at com.clickhouse.client.stream.AbstractByteArrayOutputStream.transferBytes(AbstractByteArrayOutputStream.java:43)
> 	at com.clickhouse.client.stream.AbstractByteBufferInputStream.pipe(AbstractByteBufferInputStream.java:90)
> 	at com.clickhouse.client.ClickHouseInputStream.pipe(ClickHouseInputStream.java:424)
> 	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:284)
> 	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:123)
> 	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:296)
> 	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:284)
> 	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:296)
> 	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:351)
> 	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:824)
> 	at com.clickhouse.client.ClickHouseRequest$Mutation.executeAndWait(ClickHouseRequest.java:288)
> 	at com.clickhouse.client.ClickHouseRequest$Mutation.sendAndWait(ClickHouseRequest.java:314)
> 	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeInsert(ClickHouseStatementImpl.java:177)
> 	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeAny(InputBasedPreparedStatement.java:117)
> 	at com.clickhouse.jdbc.internal.AbstractPreparedStatement.executeLargeBatch(AbstractPreparedStatement.java:85)
> 	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:568)
> 
> "pool-2-thread-9" #22 prio=5 os_prio=31 tid=0x00007fea6d019000 nid=0x9703 runnable [0x000070000ff53000]
>    java.lang.Thread.State: RUNNABLE
> 	at java.net.SocketOutputStream.socketWrite0(Native Method)
> 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
> 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
> 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
> 	- locked <0x000000077ac5fd80> (a java.io.BufferedOutputStream)
> 	at java.io.PrintStream.write(PrintStream.java:480)
> 	- locked <0x000000077ac5fd98> (a java.io.PrintStream)
> 	at sun.net.www.http.ChunkedOutputStream.flush(ChunkedOutputStream.java:145)
> 	at sun.net.www.http.ChunkedOutputStream.write(ChunkedOutputStream.java:237)
> 	- locked <0x00000007722a8110> (a sun.net.www.http.ChunkedOutputStream)
> 	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3586)
> 	at com.clickhouse.client.stream.WrappedOutputStream.flushBuffer(WrappedOutputStream.java:19)
> 	at com.clickhouse.client.stream.AbstractByteArrayOutputStream.transferBytes(AbstractByteArrayOutputStream.java:43)
> 	at com.clickhouse.client.stream.AbstractByteBufferInputStream.pipe(AbstractByteBufferInputStream.java:90)
> 	at com.clickhouse.client.ClickHouseInputStream.pipe(ClickHouseInputStream.java:424)
> 	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:284)
> 	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:123)
> ```
The background of the test is to insert more data in parallel

**Comment by rrsunhome** [comment]
**Parallel execution**
![image](https://user-images.githubusercontent.com/34878555/224305927-4525b7e7-a340-49fe-96c5-874e428c991e.png)
**Single synchronous execution**
![image](https://user-images.githubusercontent.com/34878555/224306344-baec87f2-c05e-4afa-ae79-34045e7cae7c.png)

**Comment by zhicwu** [comment]
Hi @rrsunhome, thanks for sharing the test results. What's the expectation? Same or even lower latency compare to single thread? Have you tried async insert and/or adjust server threads?

Looking at the stack trace, it seems there's waits for writing. Did you check server status?

**Comment by rrsunhome** [comment]
> 你好@rrsunhome，感谢分享测试结果。期望是什么？与单线程相比，延迟相同甚至更低？您是否尝试过异步插入和/或调整服务器线程？
> 
> 查看堆栈跟踪，似乎等待写入。你检查服务器状态了吗？

Thank you for your reply

The expectation is the same as the single-thread insertion delay

The cpu usage of the server is very high, and the high latency should be caused by this
