### ISSUE TITLE
Stream Processing Issue

### ISSUE THREAD

**Issue by wudstrand** [ClickHouse/clickhouse-java#1299]
### Describe the bug
When querying our clickhouse cluster we are getting intermittent 500 error due to an error with the processing of the data streamed back from clickhouse. I have been able to trace the bug through the client library and it is looks like it is an issue with how the stream of data is chucked into rows and/or processed.

### Expected Behavior
When data is queried it is processed correctly.

### Steps to reproduce
I am unable to give exact steps of how to reproduce this bug, and _**I have noticed this tends to happen when querying large amounts of records**_. Here are the steps and some of the stack trace from my application. 

1. Send a basic select query through the `selectMany` function.
```SQL
SELECT implied_forward_ask, iv_bid, expiration_date, date, bid, as_of, t, underlying_bid, implied_forward_bid, strike_price, option_type, underlying_ask, iv_ask, underlying_ticker, ask, root
FROM equity_option
WHERE underlying_ticker = '^IDX'
ORDER BY date DESC
LIMIT 50000
OFFSET 0
```
2. Set a break point on the exception being thrown in this example it would be the `NumberFormatException`
3. Move back up the stack to `ClickHouseTabSeparatedProcessor.readAndFill` method
4. View the `CurrentRow` Object and see that it contains data that is separated by `\n` rather then a `<TAB>`, which is causing multiple column to be serialized as a single column type/value leading to the error.
```text
# Problematic Byte Fragment
ByteFragment{[0<TAB>PUT<TAB>4141.95<TAB>0.2745460405078881<TAB>^IDX<TAB>113.2<TAB>IDXZ\n4096.6<TAB>0.3107502233281483<TAB>2022-10-21 20:00:00.000000000<TAB>2022-08-02 00:00:00.000000000<TAB>28.8<TAB>2022-08-02 20:00:00.00000000.51<TAB>0.1837537276276108<TAB>^IDX<TAB>51.8<TAB>SPXW
], start=0, len=205}

# Byte Fragment Issue
<TAB>IDXZ/n4096.6<TAB>
```
5. It also seems that the data (i.e. the column value) isnt correctly correlated to the right column. Causing an attempt to cast column values to the incorrect type like a string to a number.

### Code example
```kotlin
@Configuration
@EnableR2dbcRepositories(
    basePackages = ["com.algoralabs.data.repository"],
    databaseClientRef = "clickhouse"
)
class ClickhouseClient(private val clickhouseConfig: ClickhouseConfig) : AbstractR2dbcConfiguration() {
    override fun connectionFactory(): ConnectionFactory {
        return ConnectionFactories.get(clickhouseConfig.connectionString())
    }

    @Bean(name = ["clickhouse"])
    fun client(): DatabaseClient {
        val factory = connectionFactory()

        return DatabaseClient
            .builder()
            .bindMarkers(getDialect(factory).bindMarkersFactory)
            .connectionFactory(factory)
            .build()
    }

    override fun getDialect(connectionFactory: ConnectionFactory): R2dbcDialect {
        return MySqlDialect()
    }
}
```

```kotlin
fun selectMany(query: Query): Flux<Map<String, Any>> {
      val queryString = query.toSql()

      return databaseClient   // i.e. the clickhouse client from above
          .sql(queryString)
          .fetch()
          .all()
}
```

### Error log
**NOTE:** The error we get changes from time to time but it is always a problem with formatting the data to a specific type.
```
java.lang.NumberFormatException: For input string: "PUT"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler com.algoralabs.data.controller.datasets.QueryController#getTimeSeries(TimeseriesQuery, UUID, Set, Set) [DispatcherHandler]
	*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/timeseries" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[na:na]
		at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[na:na]
		at java.base/java.lang.Double.parseDouble(Double.java:543) ~[na:na]
		at com.clickhouse.data.value.ClickHouseDoubleValue.update(ClickHouseDoubleValue.java:257) ~[clickhouse-data-0.4.1.jar:clickhouse-data 0.4.1 (revision: 4a6940b)]
		at com.clickhouse.data.value.ClickHouseDoubleValue.update(ClickHouseDoubleValue.java:13) ~[clickhouse-data-0.4.1.jar:clickhouse-data 0.4.1 (revision: 4a6940b)]
		at com.clickhouse.data.format.ClickHouseTabSeparatedProcessor.readAndFill(ClickHouseTabSeparatedProcessor.java:74) ~[clickhouse-data-0.4.1.jar:clickhouse-data 0.4.1 (revision: 4a6940b)]
		at com.clickhouse.data.ClickHouseDataProcessor.nextRecord(ClickHouseDataProcessor.java:134) ~[clickhouse-data-0.4.1.jar:clickhouse-data 0.4.1 (revision: 4a6940b)]
		at com.clickhouse.data.ClickHouseDataProcessor.access$000(ClickHouseDataProcessor.java:25) ~[clickhouse-data-0.4.1.jar:clickhouse-data 0.4.1 (revision: 4a6940b)]
		at com.clickhouse.data.ClickHouseDataProcessor$RecordsIterator.next(ClickHouseDataProcessor.java:51) ~[clickhouse-data-0.4.1.jar:clickhouse-data 0.4.1 (revision: 4a6940b)]
		at com.clickhouse.data.ClickHouseDataProcessor$RecordsIterator.next(ClickHouseDataProcessor.java:37) ~[clickhouse-data-0.4.1.jar:clickhouse-data 0.4.1 (revision: 4a6940b)]
		at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812) ~[na:na]
		at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294) ~[na:na]
		at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206) ~[na:na]
		at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:169) ~[na:na]
		at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300) ~[na:na]
		at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.hasNext(FluxIterable.java:600) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.slowPath(FluxIterable.java:673) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxIterable$IterableSubscriptionConditional.request(FluxIterable.java:623) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.request(FluxMap.java:295) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.request(FluxMap.java:295) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.request(FluxMap.java:295) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.request(FluxMap.java:295) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxHandle$HandleSubscriber.request(FluxHandle.java:269) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxFlatMap$FlatMapInner.onSubscribe(FluxFlatMap.java:965) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxHandle$HandleSubscriber.onSubscribe(FluxHandle.java:87) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onSubscribe(FluxMap.java:194) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onSubscribe(FluxMap.java:194) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onSubscribe(FluxMap.java:194) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onSubscribe(FluxMap.java:194) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:179) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxStream.subscribe(FluxStream.java:69) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.Flux.subscribe(Flux.java:8642) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.MonoFlatMapMany.subscribeOrReturn(MonoFlatMapMany.java:49) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.Flux.subscribe(Flux.java:8628) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:427) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1839) ~[reactor-core-3.4.27.jar:3.4.27]
		at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:96) ~[reactor-core-3.4.27.jar:3.4.27]
		at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[na:na]
		at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907) ~[na:na]
		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
		at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1705) ~[na:na]
		at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
		at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

#### Environment
Spring version | 2.7.9
-- | --
Java Version | 11.0.5
Kotlin Version | 1.6.21
Database Driver | r2dbc
clickhouse-client | 0.4.1
clickhouse-r2dbc | 0.4.1

#### ClickHouse server
  | Prod | Dev
-- | -- | --
Clickhouse Cluster Version | 21.10.5 | 21.10.5
Deployment Type | K8s using clickhouse operator | K8s using clickhouse operator
Shards | 2 | 2
Replicas | 2 | 2
Zookeeper Version | 3.8.0-5a02a05eddb59aee6ac762f7ea82e92a68eb9c0f | 3.6.3--6401e4ad2087061bc6b9f80dec2d69f2e3c8660a
Zookeeper Nodes | 2 | 1

##### Problematic Table
```
CREATE TABLE equity_option_local on cluster '{cluster}'
(
    underlying_ticker   String,
    root                String,
    as_of               DateTime64(9, 'UTC'),
    date                DateTime64(9, 'UTC'),
    expiration_date     DateTime64(9, 'UTC'),
    strike_price        Float64,
    option_type         String,
    bid                 Float64,
    ask                 Float64,
    underlying_bid      Float64,
    underlying_ask      Float64,
    implied_forward_bid Float64,
    implied_forward_ask Float64,
    iv_bid              Float64,
    iv_ask              Float64,
    t                   Float64
)
ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}', '{replica}')
ORDER BY (underlying_ticker, date, as_of, option_type, expiration_date, strike_price)
SETTINGS index_granularity = 8192;

CREATE TABLE equity_option ON CLUSTER '{cluster}' AS equity_option_local
ENGINE = Distributed('{cluster}', default, equity_option_local, sipHash64(date));
```

##### Sample Data (csv)
```
underlying_ticker,root,as_of,date,expiration_date,strike_price,option_type,bid,ask,underlying_bid,underlying_ask,implied_forward_bid,implied_forward_ask,iv_bid,iv_ask,t
^IDX,IDXZ,2008-01-01 20:00:00.000000,2008-01-01 00:00:00.000000,2008-07-26 20:00:00.000000,2625,CALL,12.5,12.9,2802.8,2866.48,2847.1,2849.2,0.1939326906817161,0.1958139311395899,0.1368953503494253
^IDX,IDXZ,2008-01-01 20:00:00.000000,2008-01-01 00:00:00.000000,2008-07-26 20:00:00.000000,2630,CALL,12.9,13.3,2802.8,2866.48,2847.1,2849.3,0.1926174763560995,0.1944582305174519,0.1368953503494253
^IDX,IDXZ,2008-01-01 20:00:00.000000,2008-01-01 00:00:00.000000,2008-07-26 20:00:00.000000,2635,CALL,13.3,13.8,2802.8,2866.48,2847.1,2849.2,0.1911801050678516,0.1934292005138392,0.1368953503494253
^IDX,IDXZ,2008-01-01 20:00:00.000000,2008-01-01 00:00:00.000000,2008-07-26 20:00:00.000000,2640,CALL,13.8,14.3,2802.8,2866.48,2847.1,2849.2,0.1901514352741574,0.1923484311111607,0.1368953503494253
^IDX,IDXZ,2008-01-01 20:00:00.000000,2008-01-01 00:00:00.000000,2008-07-26 20:00:00.000000,2645,CALL,14.3,14.8,2802.8,2866.48,2847.2,2849.2,0.1890717378650079,0.191219528617884,0.1368953503494253
^IDX,IDXZ,2008-01-01 20:00:00.000000,2008-01-01 00:00:00.000000,2008-07-26 20:00:00.000000,2650,CALL,14.8,15.3,2802.8,2866.48,2847.2,2849.2,0.1878846558925528,0.1899855463275047,0.1368953503494253
^IDX,IDXZ,2008-01-01 20:00:00.000000,2008-01-01 00:00:00.000000,2008-07-26 20:00:00.000000,2655,CALL,15.4,15.8,2802.8,2866.48,2847.3,2849.3,0.1870956078410539,0.1887390309095967,0.1368953503494253
^IDX,IDXZ,2008-01-01 20:00:00.000000,2008-01-01 00:00:00.000000,2008-07-26 20:00:00.000000,2660,CALL,15.9,16.4,2802.8,2866.48,2847.4,2849.3,0.1857818335746029,0.1877917863971369,0.1368953503494253
^IDX,IDXZ,2008-01-01 20:00:00.000000,2008-01-01 00:00:00.000000,2008-07-26 20:00:00.000000,2665,CALL,16.5,17.0,2802.8,2866.48,2847.3,2849.2,0.1846999050260745,0.186665285191279,0.1368953503494253
```

**Comment by zhicwu** [comment]
Hi @wudstrand, thanks for the report and appreciate for all the details you provided. I think you're right that there's issue deserializing data in text format, but it might not relate the PR you commented.

Could you help me to understand the use case? Is there any specific reason of using `TabSeparated` data format instead of `RowBinary`? The latter is the default data format as it supports more data types, well-tested, and a few times faster than the former.

Lastly, it's a bit off the topic, but I want to comment that we should never use float for money. Please consider to change to decimal instead.

**Comment by wudstrand** [comment]
We are making a generic API for querying datasets and are using the code above along with the clickhouse r2dbc package to achieve this. In the example code we are running raw sql. The processor defaulted to tab separated. How would I change it to use the row binary?

**Comment by zhicwu** [comment]
Sorry for the inconvenience. r2dbc driver should set preferred format like jdbc.

You may add format=RowBinayWithNamesAndTypes in your connection string.

**Comment by wudstrand** [comment]
Do you have an example, or a link to documentation on this?

**Comment by wudstrand** [comment]
@zhicwu So I tried the following connection string `r2dbc:clickhouse://user:password@127.0.0.1:8123/default?format=RowBinayWithNamesAndTypes` and the formatter did not change. I tried to debug the issue and noticed that the config provided in the connection string wasnt getting passed to the ClickhouseClientBuilder ([see trace below](#clickhouse-client-builder-config-trace)) and that the default formatter was set to the tab formatter ([see trace below](#tab-formatter-default-trace)).


### Clickhouse Client Initialization
Here is how I am setting up my clickhouse client in spring. 
```kotlin
@Configuration
@EnableR2dbcRepositories(
    basePackages = ["com.algoralabs.data.repository"],
    databaseClientRef = "clickhouse"
)
class ClickhouseClient(private val clickhouseConfig: ClickhouseConfig) : AbstractR2dbcConfiguration() {
    override fun connectionFactory(): ConnectionFactory {
        return ConnectionFactories.get(clickhouseConfig.connectionString())
    }

    @Bean(name = ["clickhouse"])
    fun client(): DatabaseClient {
        val factory = connectionFactory()

        return DatabaseClient
            .builder()
            .bindMarkers(getDialect(factory).bindMarkersFactory)
            .connectionFactory(factory)
            .build()
    }

    override fun getDialect(connectionFactory: ConnectionFactory): R2dbcDialect {
        return MySqlDialect()
    }
}
```

### Clickhouse Client Builder Config Trace
- [clickhouse-client - ClickHouseClientBuilder:427](https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClientBuilder.java#L427)
- [clickhouse-client - ClickHouseClientBuilder:403-409](https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseClientBuilder.java#L403-L409)

### Tab Formatter Default Trace
- [clickhouse-client - ClickHouseClientConfig:291](https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-client/src/main/java/com/clickhouse/client/ClickHouseConfig.java#L291)
- [clickhouse-client - ClickHouseDefaults:56](https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-client/src/main/java/com/clickhouse/client/config/ClickHouseDefaults.java#L56)
- [clickhouse-data - ClickHouseDataConfig:136](https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-data/src/main/java/com/clickhouse/data/ClickHouseDataConfig.java#L136 )

**Comment by zhicwu** [comment]
Thanks @wudstrand, looks like R2DBC driver does not handle connection string very well, which I'll fix in a new PR.

Have you tried to specify custom [option](https://r2dbc.io/spec/0.8.0.M8/api/io/r2dbc/spi/Option.html)?

https://github.com/ClickHouse/clickhouse-java/blob/90fc6b6f747255efb68441744d250bf9668d4087/clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/connection/ClickHouseConnectionFactoryProvider.java#L78-L83

**Comment by wudstrand** [comment]
@zhicwu I tried to specify a custom option in the connection factory but that didnt work. After some debugging it looks like format is not a supported connection query parameter. When will you have a PR opened for this issue? It is blocking some time sensitive work for me.

![Screenshot 2023-03-29 at 9 14 44 AM](https://user-images.githubusercontent.com/10553702/228586458-41564411-27c6-4841-ac1c-4a9925f11363.png)

```kotlin
@Configuration
@EnableR2dbcRepositories(
    basePackages = ["com.algoralabs.data.repository.clickhouse"],
    databaseClientRef = "clickhouse"
)
class ClickhouseClient(private val databaseConfig: DatabaseConfig) : AbstractR2dbcConfiguration() {
    override fun connectionFactory(): ConnectionFactory {
        val connectionOptions = ConnectionFactoryOptions.parse(databaseConfig.CLICKHOUSE)
            .mutate()
            .option(Option.valueOf("format"), ClickHouseFormat.RowBinaryWithNamesAndTypes)
            .build()
        return ConnectionFactories.get(connectionOptions)
    }

    @Bean(name = ["clickhouse"])
    fun client(): DatabaseClient {
        val factory = connectionFactory()

        return DatabaseClient
            .builder()
            .bindMarkers(getDialect(factory).bindMarkersFactory)
            .connectionFactory(factory)
            .build()
    }

    override fun getDialect(connectionFactory: ConnectionFactory): R2dbcDialect {
        // TODO replace with custom dialect
        return MySqlDialect()
    }
}
```

**Comment by wudstrand** [comment]
@zhicwu Any update? What is the timeline for this issue? It is blocking some time sensitive work for me.

**Comment by wudstrand** [comment]
@zhicwu 
> @zhicwu Any update? What is the timeline for this issue? It is blocking some time sensitive work for me.

**Comment by zhicwu** [comment]
Apologies, @wudstrand! I'm about to resume the work this weekend. I think I can create a patch release v0.4.3 for this, and hopefully a few more issues, by next Monday. Before that, I'll submit a PR to fix this issue tomorrow and it would be great if you can then verify the nightly build prior to the patch release. Sounds good?
