### ISSUE TITLE
How to connect to clickhouse through clickhouse-grpc-client?

### ISSUE THREAD

**Issue by GerryYuan** [ClickHouse/clickhouse-java#1300]
clickhouse-grpc-client use grpc protocol, JDK11, then throw ClickHouseException, why?
```
<dependency>
      <groupId>com.clickhouse</groupId>
      <artifactId>clickhouse-grpc-client</artifactId>
      <version>0.4.2</version>
</dependency>
```
```java
final ClickHouseNode server = ClickHouseNode.builder().host("127.0.0.1").port(ClickHouseProtocol.GRPC)
            .credentials(ClickHouseCredentials.fromUserAndPassword(config.getUser(), config.getPassword())).build();
final ClickHouseClient client = ClickHouseClient.newInstance(server.getProtocol());
            this.request = client.read(server).compressServerResponse(false).decompressClientRequest(false);
client.query("drop table if exists java_client_example_table").execute().get()
```
throw ClickHouseException
```java
Caused by: com.clickhouse.client.ClickHouseException: UNAVAILABLE: Network closed for unknown reason, server ClickHouseNode [uri=grpc://127.0.0.1:9100/default]@334622429
	at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:168)
	at com.clickhouse.client.grpc.ClickHouseGrpcClientImpl.sendAsync(ClickHouseGrpcClientImpl.java:346)
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:273)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.Status.asRuntimeException(Status.java:539)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:576)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:757)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:736)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	... 3 more
```

**Comment by GerryYuan** [comment]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/11907624/227730077-2a7e8dc2-0db9-4596-9f8a-4b62ff009e64.png">

DBMS: ClickHouse (ver. 23.2.4.12)
Case sensitivity: plain=exact, delimited=exact
Driver: ClickHouse JDBC Driver (ver. 0.4.0 (revision: 3a53cf1), JDBC4.2)

**Comment by zhicwu** [comment]
Sorry for the inconvenience. r2dbc driver should set preferred format like jdbc.

You may add `format=RowBinayWithNamesAndTypes` in your connection string.

**Comment by GerryYuan** [comment]
> Hi @GerryYuan, did you see any error on server? gRPC is experimental and not suitable for production. It's reserved only for testing purpose and I'll drop it someday.

There is no error message on the server. It feels that the server does not retain the data that accepts this port when it starts. If grpc-client is not recommended, which effective method is recommended to help me operate ck?

**Comment by zhicwu** [comment]
> If grpc-client is not recommended, which effective method is recommended to help me operate ck?

I think it's better to start with JDBC driver. In the case you need to use Java client, it's better to stay with http protocol for now. For details, please refer to examples at [here](https://github.com/ClickHouse/clickhouse-java/tree/main/examples).
