### ISSUE TITLE
Submit Spark in Java : No client available issue

### ISSUE THREAD

**Issue by sofriendcom** [ClickHouse/clickhouse-java#1303]
### Steps to reproduce
1.  Package Spark JAR in java
2. sparkApplication.startApplication()
3. No client available

## test result
- Spark JAR in scala is working fine.
- cc.blynk.clickhouse.ClickHouseDriver is working fine.
- Run in DIRECT Code is working fine. - follow code 
- only not working com.clickhouse.jdbc.ClickHouseDriver and spark submit in JAVA Jar
---------
```
public class StartTest {
    @Test
    public void testStart() throws Exception {
        // String path = "/Users/sofriend/storage/job/2001.json";
        // Start.main(new String[]{path});

        Properties prop = new Properties();
        // prop.setProperty("driver", "com.clickhouse.jdbc.ClickHouseDriver");
        prop.setProperty("user", "pduser");
        prop.setProperty("password", "rhtmxm");
        String url = "jdbc:clickhouse://192.168.44.34:9000/test";
        String tableName = "source_1679899992461000093";
        try {
            // Class.forName("com.clickhouse.jdbc.ClickHouseDriver");
            String countQuery = "(select count(1) from " + tableName + ") as pz";
            Row row = SparkUtil.getSparkSession().read().jdbc(url, countQuery, prop).first();
            System.out.println( row.getDecimal(0));
            Row row2 = SparkUtil.getSparkSession().read().jdbc(url, countQuery, prop).first();
            System.out.println( row2.getDecimal(0));
        }
        catch(Exception e) {
            e.printStackTrace();
        }
    }
}
```

## only not working in spark submit java.
- ClickHouseDriver: ClickHouse Driver 0.0.0.0(JDBC: 0.0.0.0) registered
  - is ok? 0.0.0.0
-  Handling java.net.ConnectException: No client available(failover=0, retry=0)
  - this is problem.

follow log
------------
```
[14:35:07.339] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 **DEBUG ClickHouseDriver: ClickHouse Driver 0.0.0.0(JDBC: 0.0.0.0) registered**
[14:35:07.341] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG JDBCOptions: Keytab path found, assuming manual upload
[14:35:07.352] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG ConnectionProvider: Loaded built-in provider: org.apache.spark.sql.execution.datasources.jdbc.connection.BasicConnectionProvider@11399548
[14:35:07.352] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG ConnectionProvider: Loaded built-in provider: org.apache.spark.sql.execution.datasources.jdbc.connection.DB2ConnectionProvider@58164e9a
[14:35:07.352] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG ConnectionProvider: Loaded built-in provider: org.apache.spark.sql.execution.datasources.jdbc.connection.MariaDBConnectionProvider@76e6c070
[14:35:07.352] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG ConnectionProvider: Loaded built-in provider: org.apache.spark.sql.execution.datasources.jdbc.connection.MSSQLConnectionProvider@f03ee8f
[14:35:07.352] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG ConnectionProvider: Loaded built-in provider: org.apache.spark.sql.execution.datasources.jdbc.connection.PostgresConnectionProvider@5e5a8718
[14:35:07.353] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG ConnectionProvider: Loaded built-in provider: org.apache.spark.sql.execution.datasources.jdbc.connection.OracleConnectionProvider@4e50ae56
5
[14:35:07.353] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG JDBCOptions: Keytab path found, assuming manual upload
2
[14:35:07.354] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG JDBCOptions: Keytab path found, assuming manual upload
[14:35:07.354] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG BasicConnectionPro**vider: JDBC connection initiated with URL: jdbc:clickhouse://192.168.44.34:8123/test and properties: {password=rhtmxm,** driver=com.clickhouse.jdbc.ClickHouseDriver, dbtable=(select count(1) from source_1679903931850000201) as pz, user=pduser, url=jdbc:clickhouse://192.168.44.34:8123/test}
[14:35:07.354] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG ClickHouseDriver: Creating connection
[14:35:07.376] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG ClickHouseConnectionImpl: Connecting to: ClickHouseNode [uri=http://192.168.44.34:8123/test, options={driver=com.clickhouse.jdbc.ClickHouseDriver,dbtable=(select count(1) from source_1679903931850000201) as pz,url=jdbc:clickhouse://192.168.44.34:8123/test}]@1398196566
[14:35:07.376] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 DEBUG ClickHouseClientBuilder$Agent: Failed to find client for ClickHouseNode [uri=http://192.168.44.34:8123/test, options={driver=com.clickhouse.jdbc.ClickHouseDriver,dbtable=(select count(1) from source_1679903931850000201) as pz,url=jdbc:clickhouse://192.168.44.34:8123/test}]@1398196566
[14:35:07.376] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 23/03/28 14:35:07 **DEBUG ClickHouseClientBuilder$Agent: Handling java.net.ConnectException: No client available(failover=0, retry=0)
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] java.sql.SQLException: No client available, server ClickHouseNode [uri=http://192.168.44.34:8123/test, options={driver=com.clickhouse.jdbc.ClickHouseDriver,dbtable=(select count(1) from source_1679903931850000201) as pz,url=jdbc:clickhouse://192.168.44.34:8123/test}]@1398196566**
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
SqlExceptionUtils.java:85
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
SqlExceptionUtils.java:31
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
SqlExceptionUtils.java:90
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:131)
ClickHouseConnectionImpl.java:131
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:334)
ClickHouseConnectionImpl.java:334
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:287)
ClickHouseConnectionImpl.java:287
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:157)
ClickHouseDriver.java:157
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:41)
ClickHouseDriver.java:41
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at org.apache.spark.sql.execution.datasources.jdbc.connection.BasicConnectionProvider.getConnection(BasicConnectionProvider.scala:49)
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at org.apache.spark.sql.execution.datasources.jdbc.connection.ConnectionProvider$.create(ConnectionProvider.scala:77)
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$createConnectionFactory$1(JdbcUtils.scala:64)
[14:35:07.377] [INFO ] org.apache.spark.launcher.app.Start      [] [:] 	at org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.getQueryOutputSchema(JDBCRDD.scala:62)
------------------
```
java 11
Clickhouse in docker

**Comment by zhicwu** [comment]
Hi @sofriendcom, judging from `ClickHouse Driver 0.0.0.0(JDBC: 0.0.0.0)`, it looks like you're using a private build of JDBC driver? Please use latest version(v0.4.2) and add classifier(`http` or `all`) if the default artifact does not work for you.

**Comment by sofriendcom** [comment]
@zhicwu  i use 0.4.2:all  and 0.4.1, 0.3.x.. all same issue..

**Comment by zhicwu** [comment]
Could you check classpath to understand where the `ClickHouse Driver 0.0.0.0(JDBC: 0.0.0.0)` came from? You probably have duplicated classes there, try search com.clickhouse in classpath including all jars.

**Comment by sofriendcom** [comment]
this is work outside spark.  only not work in apache spark submit.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/129146085/228433305-79c33650-4863-4bd1-a470-cb7a4f618eb6.png">

there is only one clickhouse driver.

this is my gradle dependency
```
dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    implementation ( group: 'org.apache.spark', name: 'spark-core_2.12', version: '3.2.3')
    implementation ( group: 'org.apache.spark', name: 'spark-sql_2.12', version: '3.2.3')
    implementation 'org.codehaus.janino:janino:3.0.16'
    implementation group: 'org.postgresql', name: 'postgresql', version: '42.3.1'
    implementation "com.google.code.gson:gson:2.9.0"
    compileOnly 'org.projectlombok:lombok:1.18.24'
	annotationProcessor 'org.projectlombok:lombok:1.18.24'
    implementation ('com.clickhouse:clickhouse-jdbc:0.4.2:http')
    // implementation('cc.blynk.clickhouse:clickhouse4j:1.4.4')
}
```

and i'am packaging fat jar for spark submit.
```
task jar_spark(type: Jar) {
    baseName = 'patransform'
    // manifest {
    //     attributes 'Main-Class': 'com.puzzledata.transform.Start'
    // }
    zip64 true
    exclude("**/logback.xml", "**/license", "META-INF/**")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
    with jar
}
```

there is only two jdbc driver. postgresql and clickhouse.

I think that is bug why "cc.blynk.clickhouse:clickhouse4j:1.4.4" driver is working fine.

**Comment by mzitnik** [comment]
@sofriendcom did you managed to fix the issue?

**Comment by sofriend** [comment]
> 
It hasn't been fixed yet.
To solve this I am still using the "cc.blynk.clickhouse:clickhouse4j:1.4.4" driver.

**Comment by chernser** [comment]
Good day, @vitalvi! 
We will look into the issue. 

Btw, we have own implementation of Spark connector https://clickhouse.com/docs/en/integrations/apache-spark#spark-jdbc
May be it can solve the issue? 

Thanks!

**Comment by chernser** [comment]
Fixed with 0.7.2 release

**Comment by sofriendcom** [comment]
i am test with 0.8.1.
it's OK.
problem solved. thank you!!
