### ISSUE TITLE
The query failed due to special characters

### ISSUE THREAD

**Issue by fengtwo** [ClickHouse/clickhouse-java#1316]
### Describe the bug
I already have one such piece of data. I imported it from pgsql using DBeaver. There was a problem when I queried this data, but I had no problem using the terminal tool "clickhouse-client", so I suspected the driver Bug of jdbc. Also, when I wanted to insert a piece of such data, I ran into difficulties.
You can test using DBeaver or another jdbc tool. I reproduced this error using both java code and Dbeaver.
### Steps to reproduce
1. create table
```sql
CREATE TABLE IF NOT EXISTS default.test_table
(
    `id`   String DEFAULT generateUUIDv4(),
    `str`  String,

)ENGINE = MergeTree 
ORDER BY (id);
```
2. 
```sql
INSERT INTO `default`.test_table (str) VALUES
( 'PUT /get.php HTTP/1.1\015\012Host: 172.18.100.109\015\012User-Agent: curl/7.81.0\015\012Accept: */*\015\012Content-Length: 30\015\012Expect: 100-continue\015\012\015\012<?php eval(@$_GET[\'cmd\']); ?>\012');
```

### Code example
using clickhouse-client：
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/25575973/232984384-a5824274-3942-4322-a663-16db5f09d50c.png">

### Error log
clickhouse-server log:
```
2023.04.19 14:52:40.078092 [ 28694 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 107, Net Exception: Socket is not connected, Stack trace (when copying this message, always include the lines below):

0. Poco::Net::SocketImpl::error(int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) @ 0x1823e8cb in /usr/bin/clickhouse
1. Poco::Net::SocketImpl::peerAddress() @ 0x18241116 in /usr/bin/clickhouse
2. DB::HTTPServerRequest::HTTPServerRequest(std::__1::shared_ptr<DB::IHTTPContext>, DB::HTTPServerResponse&, Poco::Net::HTTPServerSession&) @ 0x153d0a57 in /usr/bin/clickhouse
3. DB::HTTPServerConnection::run() @ 0x153cf3be in /usr/bin/clickhouse
4. Poco::Net::TCPServerConnection::start() @ 0x18245a34 in /usr/bin/clickhouse
5. Poco::Net::TCPServerDispatcher::run() @ 0x182473db in /usr/bin/clickhouse
6. Poco::PooledThread::run() @ 0x183d64c7 in /usr/bin/clickhouse
7. Poco::ThreadImpl::runnableEntry(void*) @ 0x183d3efd in /usr/bin/clickhouse
8. start_thread @ 0x7ea5 in /usr/lib64/libpthread-2.17.so
9. clone @ 0xfeb0d in /usr/lib64/libc-2.17.so
 (version 22.12.5.34 (official build))
```

driver log:
```
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select http_request  from cw_dtlog where id='10002']; nested exception is java.sql.SQLException: Premature EOF, server ClickHouseNode [uri=http://172.18.33.108:8123/bot]@-944784580

	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:388)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:490)
	at com.venustech.cwaf.clickhouse.JdbcTest.select(JdbcTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.sql.SQLException: Premature EOF, server ClickHouseNode [uri=http://172.18.33.108:8123/bot]@-944784580
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:105)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:344)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:439)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
	... 37 more
Caused by: java.io.IOException: Premature EOF
	at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
	at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3482)
	at com.clickhouse.data.stream.Lz4InputStream.readFully(Lz4InputStream.java:34)
	at com.clickhouse.data.stream.Lz4InputStream.updateBuffer(Lz4InputStream.java:52)
	at com.clickhouse.data.stream.AbstractByteArrayInputStream.available(AbstractByteArrayInputStream.java:57)
	at com.clickhouse.data.format.ClickHouseRowBinaryProcessor.readColumns(ClickHouseRowBinaryProcessor.java:272)
	at com.clickhouse.data.ClickHouseDataProcessor.<init>(ClickHouseDataProcessor.java:308)
	at com.clickhouse.data.format.ClickHouseRowBinaryProcessor.<init>(ClickHouseRowBinaryProcessor.java:309)
	at com.clickhouse.data.ClickHouseDataStreamFactory.getProcessor(ClickHouseDataStreamFactory.java:56)
	at com.clickhouse.client.ClickHouseStreamResponse.<init>(ClickHouseStreamResponse.java:74)
	at com.clickhouse.client.ClickHouseStreamResponse.of(ClickHouseStreamResponse.java:51)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:128)
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:298)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:287)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:299)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:354)
	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:884)
	at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2068)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:103)
	... 40 more

```
#### Environment
* Client version:  com.clickhouse:clickhouse-jdbc 0.4.0
* Language version:
* OS: mac m1

#### ClickHouse server
* ClickHouse Server version: 22.12.5.34

**Comment by zhicwu** [comment]
Hi @fengtwo, is the query generated or created by you? You need to use either `\'` or `''` to escape single quote in string value. Alternatively, assume there's no tab in value, you can change the query to:

```sql
INSERT INTO test_table (str) format TSV
PUT /get.php HTTP/1.1\015\012Host: 172.18.100.109\015\012User-Agent: curl/7.81.0\015\012Accept: */*\015\012Content-Length: 30\015\012Expect: 100-continue\015\012\015\012<?php eval(@$_GET['cmd']); ?>\012
```

**Comment by fengtwo** [comment]
Hello, I'm so sorry! I didn't fully describe my problem. I already have one such piece of data. I imported it from pgsql using DBeaver. There was a problem when I queried this data, but I had no problem using the terminal tool "clickhouse-client", so I suspected the driver Bug of jdbc. Also, when I wanted to insert a piece of such data, I ran into difficulties.

> Hi @fengtwo, is the query generated or created by you? You need to use either `\'` or `''` to escape single quote in string value. Alternatively, assume there's no tab in value, you can change the query to:
> 
> ```sql
> INSERT INTO test_table (str) format TSV
> PUT /get.php HTTP/1.1\015\012Host: 172.18.100.109\015\012User-Agent: curl/7.81.0\015\012Accept: */*\015\012Content-Length: 30\015\012Expect: 100-continue\015\012\015\012<?php eval(@$_GET['cmd']); ?>\012
> ```

**Comment by zhicwu** [comment]
Sorry for the late response. If the data is not sensitive, you may use `select hex(<your column>)` and paste data here.

**Comment by fengtwo** [comment]
> Sorry for the late response. If the data is not sensitive, you may use `select hex(<your column>)` and paste data here.
hex(column) result
```
505554202F6765742E70687020485454502F312E315C3031355C303132486F73743A203137322E31382E3130302E3130395C3031355C303132557365722D4167656E743A206375726C2F372E38312E305C3031355C3031324163636570743A202A2F2A5C3031355C303132436F6E74656E742D4C656E6774683A2033305C3031355C3031324578706563743A203130302D636F6E74696E75655C3031355C3031325C3031355C3031323C3F706870206576616C2840245F4745545B27636D64275D293B203F3E5C303132
```

**Comment by zhicwu** [comment]
Thank you @fengtwo for providing the data.

Just tried below query DBeaver using JDBC driver v0.4.4 and it works just fine. Could you try it at your end and see if you still have the same issue?
```sql
select unhex('505554202F6765742E70687020485454502F312E315C3031355C303132486F73743A203137322E31382E3130302E3130395C3031355C303132557365722D4167656E743A206375726C2F372E38312E305C3031355C3031324163636570743A202A2F2A5C3031355C303132436F6E74656E742D4C656E6774683A2033305C3031355C3031324578706563743A203130302D636F6E74696E75655C3031355C3031325C3031355C3031323C3F706870206576616C2840245F4745545B27636D64275D293B203F3E5C303132')
```

**Comment by fengtwo** [comment]
> Thank you @fengtwo for providing the data.
> 
> Just tried below query DBeaver using JDBC driver v0.4.4 and it works just fine. Could you try it at your end and see if you still have the same issue?
> 
> ```sql
> select unhex('505554202F6765742E70687020485454502F312E315C3031355C303132486F73743A203137322E31382E3130302E3130395C3031355C303132557365722D4167656E743A206375726C2F372E38312E305C3031355C3031324163636570743A202A2F2A5C3031355C303132436F6E74656E742D4C656E6774683A2033305C3031355C3031324578706563743A203130302D636F6E74696E75655C3031355C3031325C3031355C3031323C3F706870206576616C2840245F4745545B27636D64275D293B203F3E5C303132')
> ```

hi! zhicwu. I'm glad my problem has been solved. Go your way and use driver 0.4.4.
However, there is a slight problem. On DBeaver, the 0.4.4 driver does not automatically handle dependencies. For example, I manually specified JAR packages for lz4 and grpc. But it doesn't matter, probably because version 0.4.4 was just released.

**Comment by zhicwu** [comment]
Are you using latest DBeaver? It will download all the dependencies as shown below.

![image](https://user-images.githubusercontent.com/4270380/233919611-09615cc4-2992-43a7-abb6-31d1124f6197.png)

**Comment by fengtwo** [comment]
> Are you using latest DBeaver? It will download all the dependencies as shown below.

DBeaver Version: 23.0.2.202304091457
I only have one Jar.
<img width="748" alt="image" src="https://user-images.githubusercontent.com/25575973/233920581-85447a78-87a6-4730-8538-2e84100df4bc.png">

**Comment by zhicwu** [comment]
Same here. Perhaps you can reset and download again?

**Comment by fengtwo** [comment]
> Same here. Perhaps you can reset and download again?

Ok, I'll try.
