### ISSUE TITLE
Exception when run benchmark with `Insertion.insertString`

### ISSUE THREAD

**Issue by JackyWoo** [ClickHouse/clickhouse-java#1318]
### Describe the bug
Got exception `Could not connect to Ryuk ` when run benchmark with `Insertion.insertString`.
But it is ok when run `Query.selectInt8`

### Steps to reproduce
1. java -jar target/benchmarks.jar -p client=clickhouse-jdbc -p type=default -p connection=reuse Insertion.insertString

### Error log
```
# Detecting actual CPU count: 96 detected
# JMH version: 1.36
# VM version: JDK 17.0.6, OpenJDK 64-Bit Server VM, 17.0.6+10-Ubuntu-0ubuntu120.04.1
# VM invoker: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
# VM options: <none>
# Blackhole mode: compiler (auto-detected, use -Djmh.blackhole.autoDetect=false to disable)
# Warmup: 10 iterations, 1 s each
# Measurement: 10 iterations, 1 s each
# Timeout: 10 min per iteration
# Threads: 96 threads, will synchronize iterations
# Benchmark mode: Throughput, ops/time
# Benchmark: com.clickhouse.benchmark.jdbc.Insertion.insertString
# Parameters: (client = clickhouse-jdbc, connection = reuse, statement = normal, type = default)

# Run progress: 0.00% complete, ETA 00:01:20
# Fork: 1 of 2
# Warmup Iteration   1: SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
<failure>

java.lang.IllegalStateException: Could not connect to Ryuk at localhost:49182
	at org.testcontainers.utility.RyukResourceReaper.maybeStart(RyukResourceReaper.java:132)
	at org.testcontainers.utility.RyukResourceReaper.init(RyukResourceReaper.java:42)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:224)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:104)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:109)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
	at com.clickhouse.benchmark.ServerState.doSetup(ServerState.java:91)
	at com.clickhouse.benchmark.jdbc.jmh_generated.Insertion_insertString_jmhTest._jmh_tryInit_f_serverstate2_G(Insertion_insertString_jmhTest.java:501)
	at com.clickhouse.benchmark.jdbc.jmh_generated.Insertion_insertString_jmhTest.insertString_Throughput(Insertion_insertString_jmhTest.java:73)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I do not know whether is a bug.

**Comment by zhicwu** [comment]
Thanks for the report. Just tried but I was not able to reproduce. By default, it tries to start a ClickHouse server in docker container, which is apparently no good for serious benchmarking.

Assume you have a standalone ClickHouse server for testing on a different server x.x.x.x:8123 with default account, you may change the command line to:

```
java -DdbHost=x.x.x.x -DinsertMode=table -jar target/benchmarks.jar -t 1 -p client=clickhouse-jdbc -p type=default -p connection=reuse Insertion.insertString
```

**Comment by JackyWoo** [comment]
@zhicwu Thanks.  It works.

But found another exception in normal statement(works fine with prepared statement).

```
java.sql.BatchUpdateException: Code: 62. DB::Exception: Syntax error: failed at position 86 (end of query): . Expected one of: FROM INFILE, VALUES, FORMAT, SELECT, WITH, WATCH. (SYNTAX_ERROR) (version 22.3.6.5 (official build))
, server ClickHouseNode [uri=http://10.203.24.118:8123/system, options={http_connection_provider=APACHE_HTTP_CLIENT,use_server_time_zone=false,use_time_zone=UTC,compress=true,format=RowBinaryWithNamesAndTypes}]@268275203
	at com.clickhouse.jdbc.SqlExceptionUtils.batchUpdateError(SqlExceptionUtils.java:107)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeLargeBatch(ClickHouseStatementImpl.java:782)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:752)
	at com.clickhouse.benchmark.jdbc.DriverBenchmark.processBatch(DriverBenchmark.java:106)
	at com.clickhouse.benchmark.jdbc.DriverBenchmark.executeInsert(DriverBenchmark.java:136)
	at com.clickhouse.benchmark.jdbc.Insertion.insertString(Insertion.java:61)
	at com.clickhouse.benchmark.jdbc.jmh_generated.Insertion_insertString_jmhTest.insertString_Throughput(Insertion_insertString_jmhTest.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:475)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:458)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by zhicwu** [comment]
> But found another exception in normal statement(works fine with prepared statement).

Yes it does not work for Statement due to lack of data after insert statement.

**Comment by JackyWoo** [comment]
By the way, I think we should add more types of issue template, such as: enhancement, question, features.

**Comment by chernser** [comment]
Good day, @JackyWoo! 
 May I close the issue?

**Comment by JackyWoo** [comment]
@chernser yes, please
