### ISSUE TITLE
ClickHouseRowMetadata index should start at 0

### ISSUE THREAD

**Issue by murzart** [ClickHouse/clickhouse-java#1378]
### Describe the bug
[ClickHouseRowMetadata](https://github.com/ClickHouse/clickhouse-java/blob/main/clickhouse-r2dbc/src/main/java/com/clickhouse/r2dbc/ClickHouseRowMetadata.java#L24) is starting the index at 1, but the index should be starting at 0, according to the [spec](https://github.com/r2dbc/r2dbc-spi/blob/main/r2dbc-spi/src/main/java/io/r2dbc/spi/RowMetadata.java#L33).

### Expected behaviour
Should work according to spec. Index should start at 0.

### Code example
```java
    for (int i = 0; i < rowMetadata.getColumnMetadatas().size(); i++) {
      String name = rowMetadata.getColumnMetadata(i).getName(); // failing at 0.. i + 1 works
      Object value = row.get(i); // works fine

      map.put(name, value);
    }
```
### Error log
```
java.lang.IllegalArgumentException: -1
        at java.util.stream.ReferencePipeline.skip(ReferencePipeline.java:575) ~[?:?]
        at com.clickhouse.r2dbc.ClickHouseRowMetadata.getColumnMetadata(ClickHouseRowMetadata.java:24) ~[clickhouse-r2dbc-0.4.6.jar:clickhouse-r2dbc 0.4.6 (revision: dd91e17)]
        ...
```

#### Environment
* clickhouse-jdbc version: 0.4.6

**Comment by zhicwu** [comment]
Thank you @murzart for the reporting the issue. Will raise a PR to fix this.

**Comment by KevinGuancheDarias** [comment]
If additional information helps to find out the bug location, there's a more detailed error (I was creating a new issue, but I found out this one)

As of today in the current implementation of the jdbc driver  as of 0.8.6  seems not to be working as expected, for an unknown reason the jdbc driver is using 1-index column indexes instead of 0-index that confuses the Spring `DataClassRowMapper`

I tried to workaround it by manually summing +1 to the index, but unfortunately, the DataClassRowMapper is not using a protected method to find out the index, so I would have to manually create a bigger wrapper that wraps the entire for loop

Error: 

![Image](https://github.com/user-attachments/assets/33a8d039-a00d-4968-9163-bfc83453fe75)

Note that counts returns 0 index (should return 1)

One interesting thing is that the error occurs when finding out the column by name "counts" but, the `TableSchema` class seems to have correct indexing, on the column data instance return the

![Image](https://github.com/user-attachments/assets/9aeab541-30b3-493f-b7ca-3466151f736e)

my workaround fixed the method `reader.getSchema().getColumnByIndex()`  which works like 1 index, sample, but still couldn't fix the `getColumnByName("counts").getColumnIndex()`

![Image](https://github.com/user-attachments/assets/5477a242-0095-4a07-9113-e1f68807f910)

**Comment by chernser** [comment]
Fixed in 0.9.0
https://github.com/ClickHouse/clickhouse-java/pull/2376
