### ISSUE TITLE
java.sql.BatchUpdateException: Error writing request body to server

### ISSUE THREAD

**Issue by jalili** [ClickHouse/clickhouse-java#1379]
### Describe the bug
We're using the `com.clickhouse.jdbc.ClickHouseDriver` with Spark Structured Streaming to write micro-batches to Clickhouse and it works really well. However, intermittently, we get this error. It eventually gets retried by Spark and the batch goes through. I'm just trying to understand what is the underlying cause of this error. More specifically, whether it's a network issue or not. 

We run Spark on AWS EMR and Clickhouse on a fleet of EC2 instances. We have a Load Balancer sitting between Spark (the Clickhouse-driver) and Clickhouse nodes. I have tried increasing the timeout but to no avail.

### Code example
```scala
     df.coalesce(numCoalescePartitions)
              .write
              .mode(SaveMode.Append)
              .option("driver", "com.clickhouse.jdbc.ClickHouseDriver")
              .option("batchsize", batchSize)
              .jdbc(jdbcProps.uri, table = tableName, jdbcProps.properties)
```
### Error log
```
java.sql.BatchUpdateException: Error writing request body to server, server ClickHouseNode [uri=http://master-clickhouse-lb.internal:8123/events, options={connect_timeout=15000,send_timeout=1500000,receive_timeout=1500000,socket_timeout=1500000,sslmode=NONE,jdbcCompliance=false,nullAsDefault=1}]@74960053
	at com.clickhouse.jdbc.SqlExceptionUtils.batchUpdateError(SqlExceptionUtils.java:107)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeAny(InputBasedPreparedStatement.java:154)
	at com.clickhouse.jdbc.internal.AbstractPreparedStatement.executeLargeBatch(AbstractPreparedStatement.java:85)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:754)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:713)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1(JdbcUtils.scala:868)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$saveTable$1$adapted(JdbcUtils.scala:867)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1011)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1011)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2269)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:138)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

#### Driver config:
* connect_timeout=15000
* send_timeout=1500000
* receive_timeout=1500000
* socket_timeout=1500000 (not sure whether this is used or send/received timeout or both)
* sslmode=NONE
* jdbcCompliance=false
* nullAsDefault=1
#### Environment
* Client version: 0.4.6
* OS: Amazon Linux 2

#### ClickHouse server
* ClickHouse Server version: 23.4.2.11

**Comment by zhicwu** [comment]
Hi @jalili, it seems like there is an exception originating from HttpURLConnection, which is utilized for posting queries to ClickHouse.

Since we have limited information on the client side, could you please check the system.query_log table or the error log in ClickHouse? Additionally, if there is a high volume of requests being sent to the load balancer for insertion, you may consider increasing the `request_chunk_size` option (which defaults to 4096) to minimize network calls.

**Comment by jalili** [comment]
> Since we have limited information on the client side, could you please check the system.query_log table or the error log in ClickHouse? Additionally, if there is a high volume of requests being sent to the load balancer for insertion, you may consider increasing the `request_chunk_size` option (which defaults to 4096) to minimize network calls.

Thank you for getting back to me. I have scoured Clickhouse server logs but couldn't find anything. I've also looked into the query log. I see the successful INSERTs but nothing with exceptions. Since we go through the load balancer, it's hard to narrow the exception down to a specific node so I checked them all. That's what initially lead me to think it may be a network issue between EMR/LB. 

Your suggestion about `request_chunk_size` makes a lot of sense. I'll start digging to load balancer logs/metrics to get a better understanding of the frequency of requests. I'll update the ticket with my findings.

**Comment by zhicwu** [comment]
It might be worth considering checking the `keep_alive_timeout` setting in the server configuration as well, although I cannot guarantee that it will directly resolve the issue.

**Comment by akenO8** [comment]
> We switched from using the network load balancer to using Clickhouse nodes directly and the issue has disappeared. I will update the ticket when I figure out what the root-cause was. Closed the ticket.

I have the same problem as you. Have you found the answer? thanks
