### ISSUE TITLE
How to insert map(U,V) , array(T) and etc, Nested type by ClickHouseRowBinaryStream  on 0.4.6

### ISSUE THREAD

**Issue by linkey2011** [ClickHouse/clickhouse-java#1381]
clickhouse-java  version: 0.4.6
clickhouse version：22.3.3.44

table column
```
   `myint` Int64 COMMENT 'int test',

    `myfloat` Float64 COMMENT 'float test',

    `mystring` String COMMENT 'String test',

    `myarray` Array(String) CODEC(ZSTD(1)),

    `mymap` Map(String,String),
```
insert code 
```
    static void batchInsert5(Connection conn) throws SQLException {
        String sql = String.format("insert into %s format RowBinary", "test.testtable");
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setObject(1, new ClickHouseWriter() {
                @Override
                public void write(ClickHouseOutputStream output) throws IOException {
                    int p = 10;
                    for (int i = 0; i < p; i++) {
                        BinaryStreamUtils.writeInt64(output, i);
                        BinaryStreamUtils.writeFloat64(output, new Random().nextDouble());
                        BinaryStreamUtils.writeString(output, "string ");
                        BinaryStreamUtils.writeNonNull(output);
                        BinaryStreamUtils.writeNonNull(output);
                    }

                }
            });
            ps.executeUpdate();
        }
    }
```
 

in this way, i did success insert data to table, but there was no data in column  `myarray`,`mymap`,  
There is no method that looks like writeMap()，writeArray() in class  `ClickHouseOutputStream `, `BinaryStreamUtils`
i have got some information from [issues/880](https://github.com/ClickHouse/clickhouse-java/issues/880)，but the class `ClickHouseRowBinaryProcessor ` seems to be changed in 0.4.6 .

so do you mind privode some easier  examples for  insert map(U,V) or array(T) by ClickHouseRowBinaryStream  on 0.4.6? Thx for help

btw, if i remove code  `BinaryStreamUtils.writeNonNull(output);`
i got the error log
```
Caused by: java.io.IOException: Code: 33. DB::Exception: Cannot read all data. Bytes read: 84. Bytes expected: 8152.: (at row 2)
: While executing BinaryRowInputFormat. (CANNOT_READ_ALL_DATA) (version 22.3.3.44 (official build))

        at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:184)
        at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:227)
        at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:124)
        at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349)
        at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:1056)
        at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154)
        at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeInsert(ClickHouseStatementImpl.java:318)
        ... 5 more
```

**Comment by zhicwu** [comment]
Hi @linkey2011, you may start from [this](https://github.com/ClickHouse/clickhouse-java/issues/1352#issuecomment-1537246131) and refer to below test or others in the same class on how to construct a Java object for serialization accordingly.

https://github.com/ClickHouse/clickhouse-java/blob/c25ffc62c886c0cdc1fcf8d8bf2234690c131dca/clickhouse-data/src/test/java/com/clickhouse/data/format/ClickHouseRowBinaryProcessorTest.java#L625-L644
