### ISSUE TITLE
Nested column in combination with AggregateFunction isn't working for JDBC driver

### ISSUE THREAD

**Issue by mdonkers** [ClickHouse/clickhouse-java#1389]
### Describe the bug

When creating an `AggregateFunction` with `Nested` column, the JDBC driver cannot process the column.
For example 

```sql
set flatten_nested=0;
create table test_simple_aggregate_nested(id Int8, n0 SimpleAggregateFunction(anyLast, Nested(a String,b String))) ENGINE = AggregatingMergeTree() ORDER BY (id)
```
will throw an exception that `bString` column cannot be processed, because spaces are removed while processing the column description.

### Steps to reproduce
1. Create an `AggregatingMergeTree` table with `AggregateFunction` with `Nested` column type. And `flatten_nested=0` set to leave it as Nested type instead of flattened Arrays.
2. Try to query the data using the JDBC driver

### Error log

(exception is from the IntelliJ Database integration, which used JDBC as well)

```
java.sql.SQLException: Unknown data type: bString, 
server ClickHouseNode [uri=http://localhost:8123/, 
options={custom_http_params=session_id=DataGrip_46c66044-85bd-4257-b6dd-ea2cee5bd931}]@246729261 
at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85) 
at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31) 
at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90) 
at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:120) 
at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474) 
at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:462) in RemoteStatementImpl.execute(RemoteStatementImpl.java:79) 
Caused by: java.lang.IllegalArgumentException: Unknown data type: ImplementationString 
at com.clickhouse.data.ClickHouseDataType.of(ClickHouseDataType.java:238) 
at com.clickhouse.data.ClickHouseColumn.readColumn(ClickHouseColumn.java:487) 
at com.clickhouse.data.ClickHouseColumn.parse(ClickHouseColumn.java:564) 
at com.clickhouse.data.ClickHouseColumn.readColumn(ClickHouseColumn.java:391) 
at com.clickhouse.data.ClickHouseColumn.of(ClickHouseColumn.java:536) 
at com.clickhouse.data.ClickHouseColumn.readColumn(ClickHouseColumn.java:335) 
at com.clickhouse.data.ClickHouseColumn.of(ClickHouseColumn.java:536) 
at com.clickhouse.data.format.ClickHouseRowBinaryProcessor.readColumns(ClickHouseRowBinaryProcessor.java:299) 
at com.clickhouse.data.ClickHouseDataProcessor. (ClickHouseDataProcessor.java:323) 
at com.clickhouse.data.format.ClickHouseRowBinaryProcessor. (ClickHouseRowBinaryProcessor.java:320) 
at com.clickhouse.data.ClickHouseDataStreamFactory.getProcessor(ClickHouseDataStreamFactory.java:140) 
at com.clickhouse.client.ClickHouseStreamResponse. (ClickHouseStreamResponse.java:74) 
at com.clickhouse.client.ClickHouseStreamResponse.of(ClickHouseStreamResponse.java:51) 
at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:128) 
at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280) 
at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282) 
at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294) 
at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349) 
at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:1056) 
at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154) 
at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:118) 
at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474) 
at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:462) in RemoteStatementImpl.execute(RemoteStatementImpl.java:79) ... 3 more 
```

**Comment by zhicwu** [comment]
Hi @mdonkers, thank you for reporting the issue and submitting the pull request!
