### ISSUE TITLE
NumberFormatException when parsing Array(UInt64) in TabSeparatedWithNamesAndTypes format

### ISSUE THREAD

**Issue by mixNIK999** [ClickHouse/clickhouse-java#1396]
### Describe the bug
Array containing numbers in upper half of UInt64 range is failed to be parsed in TabSeparatedWithNamesAndTypes format (and probably in any TSV fromat).

At the same time:
* Single UInt64 parses correctly
* Binary format parses correctly

### Code example
```java
import com.clickhouse.client.ClickHouseClient;
import com.clickhouse.client.ClickHouseException;
import com.clickhouse.client.ClickHouseFormat;
import com.clickhouse.client.ClickHouseNodes;
import com.clickhouse.client.ClickHouseProtocol;
import com.clickhouse.client.ClickHouseResponse;
import com.clickhouse.client.ClickHouseValue;

class CHClientLongBug {
    public static void main(String[] args) throws ClickHouseException {
        ClickHouseNodes server = ClickHouseNodes.of("http://localhost:8123");
        try (ClickHouseClient client = ClickHouseClient.newInstance(ClickHouseProtocol.HTTP)) {
            try (ClickHouseResponse response = client.connect(server)
                    .format(ClickHouseFormat.RowBinaryWithNamesAndTypes)
                    .query("SELECT [18446744073709551615]")
                    .executeAndWait()) {
                ClickHouseValue value = response.firstRecord().getValue(0);
                // ClickHouseLongArrayValue[[-1]]
                System.out.println(value);
            }

            try (ClickHouseResponse response = client.connect(server)
                    .format(ClickHouseFormat.TabSeparatedWithNamesAndTypes)
                    .query("SELECT 18446744073709551615")
                    .executeAndWait()) {
                ClickHouseValue value = response.firstRecord().getValue(0);
                // ClickHouseLongValue[18446744073709551615]
                System.out.println(value);
            }

            try (ClickHouseResponse response = client.connect(server)
                    .format(ClickHouseFormat.TabSeparatedWithNamesAndTypes)
                    .query("SELECT [18446744073709551615]")
                    .executeAndWait()) {
                // Exception in thread "main" java.lang.NumberFormatException: For input string: "18446744073709551615"
                ClickHouseValue value = response.firstRecord().getValue(0);
                System.out.println(value);
            }
        }
    }
}

```
### Error log

```
ClickHouseLongArrayValue[[-1]]
ClickHouseLongValue[18446744073709551615]
Exception in thread "main" java.lang.NumberFormatException: For input string: "18446744073709551615"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Long.parseLong(Long.java:711)
	at java.base/java.lang.Long.parseLong(Long.java:836)
	at com.clickhouse.client.data.array.ClickHouseLongArrayValue.update(ClickHouseLongArrayValue.java:417)
	at com.clickhouse.client.data.array.ClickHouseLongArrayValue.update(ClickHouseLongArrayValue.java:32)
	at com.clickhouse.client.data.ClickHouseTabSeparatedProcessor.readAndFill(ClickHouseTabSeparatedProcessor.java:252)
	at com.clickhouse.client.ClickHouseDataProcessor.nextRecord(ClickHouseDataProcessor.java:143)
	at com.clickhouse.client.ClickHouseDataProcessor.access$100(ClickHouseDataProcessor.java:21)
	at com.clickhouse.client.ClickHouseDataProcessor$RecordsIterator.next(ClickHouseDataProcessor.java:36)
	at com.clickhouse.client.ClickHouseDataProcessor$RecordsIterator.next(ClickHouseDataProcessor.java:22)
	at com.clickhouse.client.ClickHouseResponse.firstRecord(ClickHouseResponse.java:103)
	at CHClientLongBug.main(CHClientLongBug.java:35)

Process finished with exit code 1
```

#### Environment
* Client version: clickhouse-client-0.3.2-patch10
* Language version: Java 17
* OS: Mac OS Monterey

#### ClickHouse server
* ClickHouse Server version: 23.3.1.2823
* Empty DB runing in docker

**Comment by zhicwu** [comment]
Thanks for the report @mixNIK999. `UInt64` is frequently used in many scenarios especially aggregation. However, in Java, we have `long` but unfortunately it's signed. So in Java client(the lower-level API), by default, `UInt64` is mapped to `long` for memory efficiency and of course performance reason. On the other hand, in JDBC driver(high-level API), you can use `ResultSet.getDecimal()` or even `getString()` to get correct result. The implicit type conversion was taken care of by ClickHouseValue and its sub-classes.

If you need to stay with Java client, you may have to unwrap array element manually, for example:
```java
import com.clickhouse.data.ClickHouseArraySequence;
import com.clickhouse.data.value.ClickHouseLongValue;

...

ClickHouseLongValue reusedContainer = ClickHouseLongValue.ofUnsignedNull(); // please upgrade driver to v0.4.6
BigInteger i =((ClickHouseArraySequence)value).getValue(0, reusedContainer).asBigInteger();
```

**Comment by mixNIK999** [comment]
Thanks for the answer. For me RowBinary format is fine for now. Problems with TSV in my project occur only in test.

It is interesting workaround with manual unwraping, but I in a middle of migration from legacy `ru.yandex.*` driver, so I cannot upgrade up to v0.4.* untill it's over.

**Comment by mzitnik** [comment]
@zhicwu I think we can close it
