### ISSUE TITLE
Converting [com.clickhouse.jdbc.ClickHouseArray] to [float[]] is not supported

### ISSUE THREAD

**Issue by xRomZak** [ClickHouse/clickhouse-java#1405]
### Describe the bug
Trying to insert a float array to a nested structure.

### Code example
```sql
job            Nested(
  task           LowCardinality(String),
  factor         Array(LowCardinality(String)),
  workload       Array(Float32), <-- fails to insert here
  num            Array(UInt16)
)
```

### Error log
```
java.lang.UnsupportedOperationException: Converting [com.clickhouse.jdbc.ClickHouseArray] to [float[]] is not supported
	at com.clickhouse.data.ClickHouseValue.newUnsupportedException(ClickHouseValue.java:50)
	at com.clickhouse.data.value.array.ClickHouseFloatArrayValue.updateUnknown(ClickHouseFloatArrayValue.java:466)
	at com.clickhouse.data.ClickHouseValue.update(ClickHouseValue.java:1244)
	at com.clickhouse.data.value.ClickHouseObjectValue.update(ClickHouseObjectValue.java:135)
	at com.clickhouse.data.value.array.ClickHouseFloatArrayValue.update(ClickHouseFloatArrayValue.java:475)
	at com.clickhouse.data.value.array.ClickHouseFloatArrayValue.update(ClickHouseFloatArrayValue.java:30)
	at com.clickhouse.data.value.ClickHouseArrayValue.getValue(ClickHouseArrayValue.java:591)
	at com.clickhouse.data.format.BinaryDataProcessor$ArraySerializer.serialize(BinaryDataProcessor.java:106)
	at com.clickhouse.data.ClickHouseDataProcessor.write(ClickHouseDataProcessor.java:593)
```

#### Environment
* Client version: 0.4.6
* ClickHouse Server version: 23.3.8.21

**Comment by zhicwu** [comment]
@xRomZak, it's slow to use `Connection.createArrayOf()` and it seems it's still buggy. Could you set float[] using `PreparedStatement.setObject()` instead?

**Comment by chernser** [comment]
Fixed in the latest version of driver. 
Please use `Connection.createArrayOf()` and `java.sql.Connection#createStruct`
