### ISSUE TITLE
How to ignore wrong line in file using "ClickHouseClient.load"?

### ISSUE THREAD

**Issue by Dong-GuoSheng** [ClickHouse/clickhouse-java#1408]
For example:
```
CREATE TABLE test.t1
(
     `A` String,
     `B` String
)
ENGINE=MergeTree
ORDER BY A
```

vim ls.tsv
zs ls
ww
zl zl

use  ClickHouseClient.load (in clickhouse-client-*.jar) to load data to table:
```
try {
    ClickHouseNode server = ClickHouseNode.builder()
                .host(System.getProperty("chHost", "localhost"))
                .port(ClickHouseProtocol.HTTP, Integer.getInteger("chPort", 8123))
                .credentials(ClickHouseCredentials.fromUserAndPassword(
                        System.getProperty("chUser", "default"), System.getProperty("chPassword", "")))
                .options(Collections.singletonMap("input_format_allow_errors_num", "100"))
                .build();

             ClickHouseResponseSummary responseSummary = ClickHouseClient.load(server, "test.t1", "/home/dss/ls.tsv", ClickHouseCompression.LZ4, ClickHouseFormat.TSV).get();
             System.out.println(responseSummary);
         }catch (Exception e){
             e.printStackTrace();
         }
```

In my file, there may be some columns that do not conform to the table definition (such as missing fields, field type mismatch, etc.), how to ignore these error lines?
Is it possible to set parameters like input_format_allow_errors_num or input_format_allow_errors_ratio?

thank you for your help.

**Comment by Dong-GuoSheng** [comment]
> 

> ``

**Comment by zhicwu** [comment]
Hi @Dong-GuoSheng, if you prefer to use Java client API, you may use `.set('<setting>', <value>)` which will pass `setting=value` (as part or query paramter) to ClickHouse.

Alternatively, you may stay with JDBC driver and use pure SQL for that, for instance: `insert into mytable <settings> from infile 'my.csv.zst' compression 'lz4' format TSV`

**Comment by Dong-GuoSheng** [comment]
thanks.
Yes, I like to use ”ClickHouseClient.load“, it can directly load the entire file directly into the table.

but, Which object is set on?
like this?
`Properties properties=new Properties();
             properties.put("input_format_allow_errors_num", 100);
             ClickHouseFile houseFile = ClickHouseFile.of("/home/dss/Desktop/zsls.tsv", ClickHouseCompression.LZ4, ClickHouseFormat.TSV);
             try (ClickHouseClient client = ClickHouseClient. newInstance(server. getProtocol());
                  ClickHouseResponse response = client.write(server).table("test.t1").data(houseFile).options(properties).executeAndWait()) {
                 ClickHouseResponseSummary responseSummary = response. getSummary();
                 System.out.println(responseSummary);
             } catch (Exception e) {
                 e.printStackTrace();
             }`
but the task is still failed(exception)

**Comment by zhicwu** [comment]
Sorry I meant `ClickHouseRequest.set()` method. Properties on the other hand is mainly for JDBC driver.

I'd still suggest you taking the SQL approach because it's also fast(on client side), because it uses ClickHousePassThruStream to simply pass the file, compressed or not, to ClickHouse to handle.

**Comment by Dong-GuoSheng** [comment]
thanks
it is work in clickhouse-client command (first set set input_format_allow_errors_num=100;)
but in my java client demo, it is error
`try (ClickHouseClient client = ClickHouseClient.newInstance(server.getProtocol())) {
                ClickHouseRequest<?> request = client.connect(server);
                request.set("input_format_allow_errors_num", 100);
                request.set("input_format_allow_errors_ratio", 0.99);
                // request.decompressClientRequest(ClickHouseCompression.LZ4);
                // request.format(ClickHouseFormat.TSV);
                ClickHouseResponse response = request.query("insert into test.t1 from infile '/home/dss/Desktop/zsls.tsv' format TSV").executeAndWait();
                ClickHouseResponseSummary responseSummary = response.getSummary();
                System.out.println(responseSummary);
            } catch (Exception e) {
                e.printStackTrace();
            }`

com.clickhouse.client.ClickHouseException: Code: 78. DB::Exception: Query has infile and was send directly to server. (UNKNOWN_TYPE_OF_QUERY) (version 22.2.2.1)
, server ClickHouseNode [uri=http://localhost:8123/system]@-1011578356
	at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:168)
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:275)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Code: 78. DB::Exception: Query has infile and was send directly to server. (UNKNOWN_TYPE_OF_QUERY) (version 22.2.2.1)

	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:184)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:227)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:124)
	at com.clickhouse.client.AbstractClient.sendAsync(AbstractClient.java:161)
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:273)
	... 4 more

**Comment by zhicwu** [comment]
@Dong-GuoSheng, very sorry I didn't make it clear. You cannot mix the usage at this point. INSERT FROM INFILE is only supported by JDBC driver, since it requires additional work like parsing; while in Java client, you have to stay with the plain-old insert, using ClickHouseRequest.set() to adjust the behavior.

**Comment by Dong-GuoSheng** [comment]
I'm sorry, I misunderstood, because I don't know much, I think more about the client.

about JDBC driver,
in https://github.com/ClickHouse/clickhouse-java/tree/main/examples/jdbc ,
i can not find more examples  about "infile"
 
so my code like 
`try {
            Connection conn = DriverManager.getConnection("jdbc:clickhouse://127.0.0.1:8123/test?input_format_allow_errors_num=100", "default", "");

            Properties properties = new Properties();
            properties.put("input_format_allow_errors_num", 100);
            properties.put("input_format_allow_errors_ratio", 0.9);
            conn.setClientInfo(properties);
            try (Statement stmt = conn.createStatement()) {
                try {
                    ClickHouseRequest<?> request = stmt.unwrap(ClickHouseRequest.class);
                    request.set("input_format_allow_errors_num", 100);
                    ClickHouseResponse response = request.query("insert into test.t1 from infile '/home/dss/Desktop/zsls.tsv' format TSV").executeAndWait();
                    System.out.println(response.getSummary());
                } catch (Exception e) {
                    e.printStackTrace();
                }

                try {
                    ResultSet result = stmt.executeQuery("insert into test.t1 from infile '/home/dss/Desktop/zsls.tsv' format TSV");
                    System.out.println(result);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }`

but this both methods are wrong

Caused by: java.io.IOException: Code: 78. DB::Exception: Query has infile and was send directly to server. (UNKNOWN_TYPE_OF_QUERY) (version 22.2.2.1)

**Comment by zhicwu** [comment]
Just tried and below works for me. You can pass query `set input_format_allow_errors_num=100; insert into t1 from infile '~/t1.tsv'` to `stmt.executeQuery(String)`.

```sql
drop table if exists t1;
create table t1(a String, b String) engine=MergeTree order by a;

{% shell:
cat << EOF > ~/t1.tsv
zs	ls
ww
zl	zl
EOF
%}

truncate table t1;
set input_format_allow_errors_num=100;
insert into t1 from infile '~/t1.tsv';

select * from t1
```

**Comment by Dong-GuoSheng** [comment]
thanks.
it is work  on clickhouse-client command.

I think that since the clickhouse-client command line mode is OK, it is possible to use "clickhouse-cli-client" at the bottom layer,
but,i readed "static Process startProcess(ClickHouseRequest<?> request)"  in "ClickHouseCommandLine.java",
i cann't find any process of "input_format_allow_errors_num"
Although I also set related properties in ClickHoueRequest.
like this
`
 try (Connection conn = DriverManager.getConnection("jdbc:ch:tcp://DZ01240", "default", "")) {
            conn.setClientInfo( "CustomHttpParameters", "input_format_allow_errors_num=10");
            try (Statement stmt = conn.createStatement()) {
                try {
                    ClickHouseRequest<?> request = stmt.unwrap(ClickHouseRequest.class);
                    request.set("input_format_allow_errors_num", 100);
                    request.set("input_format_allow_errors_ratio", 1);
                    ClickHouseResponse response = request.query("insert into test.t1 from infile '/home/dss/Desktop/zsls.tsv' format TSV").executeAndWait();
                    System.out.println(response.getSummary());
`

**Comment by Dong-GuoSheng** [comment]
The most original requirement is that I want to import data into clickhouse-server. At the beginning, I used clickhouse-client (--send_trace_log_level) +ssh, The data was successfully written and the number of rows was obtained (clickhouse version 22.8)

But because in other versions (such as 21.9.3), it is too complicated to get the number of successfully written data rows,
So after seeing the java client api, you can get summary(successRows)
