### ISSUE TITLE
Unable to insert large data volume bitmap

### ISSUE THREAD

**Issue by zy15081504206** [ClickHouse/clickhouse-java#1435]
### Describe the bug
Unable to insert large data volume bitmap,No problem with Insert 32 or less
### Code example
```java
        String insert = "insert into test.tag SELECT tag_code,tag_type,date,users FROM input('tag_code UInt64,tag_type UInt8,date Date,users AggregateFunction(groupBitmap,UInt64)')";
        try (PreparedStatement ps = clickHouseDataSource.getConnection().prepareStatement(insert)) {

            ps.setInt(1, 1);
            ps.setInt(2, 1);
            ps.setDate(3, new Date(System.currentTimeMillis()));
            long[] ints = LongStream.range(1, 50).toArray();
            Roaring64NavigableMap bitmap = Roaring64NavigableMap.bitmapOf(ints);
            ps.setObject(4, ClickHouseBitmap.wrap(bitmap, ClickHouseDataType.UInt64));
            ps.addBatch();
            ps.executeBatch();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
```
### Error log
java.lang.NoSuchFieldError: SERIALIZATION_MODE

	at com.clickhouse.data.value.ClickHouseBitmap$ClickHouseRoaring64NavigableMap.serializedSizeInBytesAsLong(ClickHouseBitmap.java:198)
	at com.clickhouse.data.value.ClickHouseBitmap.toByteBuffer(ClickHouseBitmap.java:591)
	at com.clickhouse.data.value.ClickHouseBitmap.toBytes(ClickHouseBitmap.java:605)
	at com.clickhouse.data.format.ClickHouseRowBinaryProcessor$BitmapSerDe.serialize(ClickHouseRowBinaryProcessor.java:50)
	at com.clickhouse.data.format.ClickHouseRowBinaryProcessor$$Lambda$839/1120887625.serialize(Unknown Source)
	at com.clickhouse.data.ClickHouseDataProcessor.write(ClickHouseDataProcessor.java:593)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:345)

#### Environment
* clickhouse-jdbc version: 0.4.6

**Comment by zhicwu** [comment]
Hi @zy15081504206, could you use a more recent version of RoaringBitmap (0.9.40+)?

**Comment by zy15081504206** [comment]
thanks
