### ISSUE TITLE
java.io.IOException: Magic is not correct - expect [-126] but got [105]

### ISSUE THREAD

**Issue by ikuncoder** [ClickHouse/clickhouse-java#1479]
java.io.IOException: Magic is not correct - expect [-126] but got [105]
	at com.clickhouse.client.data.ClickHouseLZ4InputStream.readNextBlock(ClickHouseLZ4InputStream.java:49) ~[clickhouse-grpc-client-0.3.2.7-SNAPSHOT-netty.jar!/:?]
	at com.clickhouse.client.data.ClickHouseLZ4InputStream.checkNext(ClickHouseLZ4InputStream.java:34) ~[clickhouse-grpc-client-0.3.2.7-SNAPSHOT-netty.jar!/:?]
	at com.clickhouse.client.data.ClickHouseLZ4InputStream.read(ClickHouseLZ4InputStream.java:173) ~[clickhouse-grpc-client-0.3.2.7-SNAPSHOT-netty.jar!/:?]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:?]
	at sun.nio.cs.StreamDecoder.read0(StreamDecoder.java:127) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:112) ~[?:?]
	at java.io.InputStreamReader.read(InputStreamReader.java:164) ~[?:?]
	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:123) ~[clickhouse-http-client-0.3.2.7-SNAPSHOT-shaded.jar!/:?]
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:201) ~[clickhouse-http-client-0.3.2.7-SNAPSHOT-shaded.jar!/:?]
	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:88) ~[clickhouse-http-client-0.3.2.7-SNAPSHOT-shaded.jar!/:?]
	at com.clickhouse.client.http.ClickHouseHttpClient.execute(ClickHouseHttpClient.java:114) ~[clickhouse-http-client-0.3.2.7-SNAPSHOT-shaded.jar!/:?]
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1385) ~[clickhouse-grpc-client-0.3.2.7-SNAPSHOT-netty.jar!/:?]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getTableColumns(ClickHouseConnectionImpl.java:192) ~[clickhouse-jdbc-0.3.2.7-SNAPSHOT.jar!/:clickhouse-jdbc 0.3.2.7-SNAPSHOT (revision: 019c760)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.prepareStatement(ClickHouseConnectionImpl.java:633) ~[clickhouse-jdbc-0.3.2.7-SNAPSHOT.jar!/:clickhouse-jdbc 0.3.2.7-SNAPSHOT (revision: 019c760)]
	at com.clickhouse.jdbc.ClickHouseConnection.prepareStatement(ClickHouseConnection.java:104) ~[clickhouse-jdbc-0.3.2.7-SNAPSHOT.jar!/:clickhouse-jdbc 0.3.2.7-SNAPSHOT (revision: 019c760)]
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:362) ~[druid-1.2.15.jar!/:?]
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.instantiateStatement(PreparedStatementHandler.java:86) ~[mybatis-3.5.9.jar!/:3.5.9]
	at org.apache.ibatis.executor.statement.BaseStatementHandler.prepare(BaseStatementHandler.java:88) ~[mybatis-3.5.9.jar!/:3.5.9]
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.prepare(RoutingStatementHandler.java:59) ~[mybatis-3.5.9.jar!/:3.5.9]
	at jdk.internal.reflect.GeneratedMethodAccessor652.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```[tasklist]
### Tasks
```

**Comment by mzitnik** [comment]
Can you provide a code snippet? So we could reproduce the issue

**Comment by chernser** [comment]
@ikuncoder would you please re-test with latest version (0.6.1)? I've seen it fixed. 
Thanks in advance!

**Comment by chernser** [comment]
no answer.
