### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/hc/core5/http/HttpRequest

### ISSUE THREAD

**Issue by sxh-lsc** [ClickHouse/clickhouse-java#1488]
### Code example
```
2023-11-15T13:48:08.235+08:00  WARN 1802624 --- [ckHouseWorker-1] c.c.c.h.ClickHouseHttpConnectionFactory  : Error when creating APACHE_HTTP_CLIENT, fall back to HTTP_URL_CONNECTION

java.lang.NoClassDefFoundError: org/apache/hc/core5/http/HttpRequest
	at com.clickhouse.client.http.ClickHouseHttpConnectionFactory.createConnection(ClickHouseHttpConnectionFactory.java:22) ~[clickhouse-http-client-0.5.0.jar:clickhouse-http-client 0.5.0 (revision: d384444)]
	at com.clickhouse.client.http.ClickHouseHttpClient.newConnection(ClickHouseHttpClient.java:56) ~[clickhouse-http-client-0.5.0.jar:clickhouse-http-client 0.5.0 (revision: d384444)]
	at com.clickhouse.client.http.ClickHouseHttpClient.newConnection(ClickHouseHttpClient.java:26) ~[clickhouse-http-client-0.5.0.jar:clickhouse-http-client 0.5.0 (revision: d384444)]
	at com.clickhouse.client.AbstractClient.getConnection(AbstractClient.java:198) ~[clickhouse-client-0.5.0.jar:clickhouse-client 0.5.0 (revision: d384444)]
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:90) ~[clickhouse-http-client-0.5.0.jar:clickhouse-http-client 0.5.0 (revision: d384444)]
	at com.clickhouse.client.AbstractClient.sendAsync(AbstractClient.java:161) ~[clickhouse-client-0.5.0.jar:clickhouse-client 0.5.0 (revision: d384444)]
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:273) ~[clickhouse-client-0.5.0.jar:clickhouse-client 0.5.0 (revision: d384444)]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.ClassNotFoundException: org.apache.hc.core5.http.HttpRequest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 11 common frames omitted
```
### Error log

 WARN 1802624 --- [ckHouseWorker-1] c.c.c.h.ClickHouseHttpConnectionFactory  : Error when creating APACHE_HTTP_CLIENT, fall back to HTTP_URL_CONNECTION

#### Environment
* Client version: 0.5.0
* Language version: jdk 17
* OS: linux

**Comment by mtrienis** [comment]
I think it's because the constructor is [protected](https://github.com/ClickHouse/clickhouse-java/blob/6a0856fdc4dbfed89dd2d0030f20accdec63bce8/clickhouse-http-client/src/main/java/com/clickhouse/client/http/ApacheHttpConnectionImpl.java#L76-L81)

**Comment by mzitnik** [comment]
@sxh-lsc Did you add the Apache Client HTTP library as a dependency?

**Comment by sxh-lsc** [comment]
fixed by reduce the version

**Comment by GYDOVE** [comment]
Pls are you reduce clickhouse version? Also, whether there is an alternative solution
