### ISSUE TITLE
com.clickhouse.client.ClickHouseRequestManager: module com.clickhouse.data does not declare `uses`

### ISSUE THREAD

**Issue by valodzka** [ClickHouse/clickhouse-java#1493]
### Describe the bug

When trying to upgrade from 0.3 -> 0.5 series I getting following error which I suppose cause by missing `use` declaration in `com.clickhouse.data`. 

```
java.util.ServiceConfigurationError: com.clickhouse.client.ClickHouseRequestManager: module com.clickhouse.data does not declare `uses`
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader.checkCaller(ServiceLoader.java:579)
	at java.base/java.util.ServiceLoader.<init>(ServiceLoader.java:507)
	at java.base/java.util.ServiceLoader.load(ServiceLoader.java:1654)
	at com.clickhouse.data@0.5.0/com.clickhouse.data.ClickHouseUtils.findFirstService(ClickHouseUtils.java:93)
	at com.clickhouse.data@0.5.0/com.clickhouse.data.ClickHouseUtils.getService(ClickHouseUtils.java:927)
	at com.clickhouse.client@0.5.0/com.clickhouse.client.ClickHouseRequestManager$InstanceHolder.<clinit>(ClickHouseRequestManager.java:20)
	at com.clickhouse.client@0.5.0/com.clickhouse.client.ClickHouseRequestManager.getInstance(ClickHouseRequestManager.java:32)
	at com.clickhouse.client@0.5.0/com.clickhouse.client.ClickHouseRequest.getManager(ClickHouseRequest.java:513)
	at com.clickhouse.client.http@0.5.0/com.clickhouse.client.http.ClickHouseHttpConnection.<init>(ClickHouseHttpConnection.java:363)
	at com.clickhouse.client.http@0.5.0/com.clickhouse.client.http.HttpUrlConnectionImpl.<init>(HttpUrlConnectionImpl.java:195)
	at com.clickhouse.client.http@0.5.0/com.clickhouse.client.http.ClickHouseHttpConnectionFactory.createConnection(ClickHouseHttpConnectionFactory.java:30)
	at com.clickhouse.client.http@0.5.0/com.clickhouse.client.http.ClickHouseHttpClient.newConnection(ClickHouseHttpClient.java:56)
	at com.clickhouse.client.http@0.5.0/com.clickhouse.client.http.ClickHouseHttpClient.newConnection(ClickHouseHttpClient.java:26)
	at com.clickhouse.client@0.5.0/com.clickhouse.client.AbstractClient.getConnection(AbstractClient.java:198)
	at com.clickhouse.client.http@0.5.0/com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:90)
	at com.clickhouse.client@0.5.0/com.clickhouse.client.AbstractClient.sendAsync(AbstractClient.java:161)
	at com.clickhouse.client@0.5.0/com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:273)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

jdk 21, project with JPMS enabled

**Comment by valodzka** [comment]
still actual as of 0.7.5

**Comment by chernser** [comment]
Should be fixed in the latest release. 
Please create an issue if problem still exists. 

Thanks!
