### ISSUE TITLE
Error ClickHouseFormat determination for create table statement with column named "format"

### ISSUE THREAD

**Issue by chvadim** [ClickHouse/clickhouse-java#1499]
### Describe the bug
If one creates a table with column named "format", they will receive java.lang.IllegalArgumentException: No enum constant com.clickhouse.data.ClickHouseFormat.String
### Code example
```java
        String url = "jdbc:ch://localhost:8123/default";
        ClickHouseDataSource dataSource = new ClickHouseDataSource(url, new Properties());
        ClickHouseConnection connection = dataSource.getConnection("default", null);
        connection.createStatement().execute("create table test_table( id Int16, format String) ENGINE = MergeTree() ORDER BY (id)" );
```
### Error log
java.lang.IllegalArgumentException: No enum constant com.clickhouse.data.ClickHouseFormat.String
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.clickhouse.data.ClickHouseFormat.valueOf(ClickHouseFormat.java:9)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:114)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:462)
#### Environment
* Client version: 0.5.0
* Language version: 1.8
* OS: Windows

#### ClickHouse server
* ClickHouse Server version: 23.8.2

**Comment by chernser** [comment]
not applicable for v2 as not parser in jdbc-v2
