### ISSUE TITLE
Query doesn't work: SYSTEM DROP FORMAT SCHEMA CACHE

### ISSUE THREAD

**Issue by yoelk** [ClickHouse/clickhouse-java#1549]
### Describe the bug
The following query works from clickhouse client, but not when connecting via JDBC:
`SYSTEM DROP FORMAT SCHEMA CACHE`

### Steps to reproduce
1. Use DBeaver to connect to a CH database using JDBC clickhouse driver (version 0.5.0)
2. execute the query: `SYSTEM DROP FORMAT SCHEMA CACHE`

### Expected behaviour
Schema caches should be dropped and query should be successful

### Code example
* tested with latest python package (`clickhouse-driver==0.2.7`)

```python
from clickhouse_driver import Client
client: Client = Client(**config)
print(client.execute("SYSTEM DROP FORMAT SCHEMA CACHE"))
```
### Error log
```
/Users/joel/workspace/virtualenvs/frontend/bin/python /Users/joel/tmp/proto/test_ch_dict_timings.py users_enrichment joel_mysql_users 
Traceback (most recent call last):
  File "/Users/joel/tmp/proto/test_ch_dict_timings.py", line 213, in <module>
    print(client.execute("SYSTEM DROP FORMAT SCHEMA CACHE"))
  File "/Users/joel/workspace/virtualenvs/frontend/lib/python3.9/site-packages/clickhouse_driver/client.py", line 382, in execute
    rv = self.process_ordinary_query(
  File "/Users/joel/workspace/virtualenvs/frontend/lib/python3.9/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/Users/joel/workspace/virtualenvs/frontend/lib/python3.9/site-packages/clickhouse_driver/client.py", line 213, in receive_result
    return result.get_result()
  File "/Users/joel/workspace/virtualenvs/frontend/lib/python3.9/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/Users/joel/workspace/virtualenvs/frontend/lib/python3.9/site-packages/clickhouse_driver/client.py", line 229, in packet_generator
    packet = self.receive_packet()
  File "/Users/joel/workspace/virtualenvs/frontend/lib/python3.9/site-packages/clickhouse_driver/client.py", line 246, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 62.
DB::Exception: Syntax error: failed at position 13 ('FORMAT'): FORMAT SCHEMA CACHE. Expected one of: DNS CACHE, MARK CACHE, UNCOMPRESSED CACHE, INDEX MARK CACHE, INDEX UNCOMPRESSED CACHE, MMAP CACHE, QUERY CACHE, FILESYSTEM CACHE, SCHEMA CACHE, S3 CLIENT CACHE, REPLICA, DATABASE REPLICA. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0xbaded44 in /usr/bin/clickhouse
1. ? @ 0x808eb00 in /usr/bin/clickhouse
2. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, String const&, bool, unsigned long, unsigned long) @ 0x118a7d90 in /usr/bin/clickhouse
3. ? @ 0x106c7748 in /usr/bin/clickhouse
4. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x106c7184 in /usr/bin/clickhouse
5. DB::TCPHandler::runImpl() @ 0x11279ef4 in /usr/bin/clickhouse
6. DB::TCPHandler::run() @ 0x1128c524 in /usr/bin/clickhouse
7. Poco::Net::TCPServerConnection::start() @ 0x11ecf104 in /usr/bin/clickhouse
8. Poco::Net::TCPServerDispatcher::run() @ 0x11ed0620 in /usr/bin/clickhouse
9. Poco::PooledThread::run() @ 0x120836dc in /usr/bin/clickhouse
10. Poco::ThreadImpl::runnableEntry(void*) @ 0x12080fa4 in /usr/bin/clickhouse
11. ? @ 0x7d5c8 in /usr/lib/aarch64-linux-gnu/libc.so.6
12. ? @ 0xe5d1c in /usr/lib/aarch64-linux-gnu/libc.so.6


Process finished with exit code 1
```

#### Environment
* Client version: CH JDBC client = 0.5.0, or python package: clickhouse-driver==0.2.7
* Language version:
* OS: macOS

#### ClickHouse server
* ClickHouse Server version: 24.2.1.1068

**Comment by chernser** [comment]
related issue https://github.com/ClickHouse/ClickHouse/issues/61347
Works on latest version .
