### ISSUE TITLE
Why is the value of my BigDecimal getting scaled up when I write it?

### ISSUE THREAD

**Issue by GaN601** [ClickHouse/clickhouse-java#1555]
### Describe the bug
![image](https://github.com/ClickHouse/clickhouse-java/assets/80253667/b4554238-f5ff-4986-a536-6b792eeccb85)

### Steps to reproduce
1.  set decimal 1362957524934568911617063.559879
2. table column: amount Decimal(38, 18)

### Code example
```java
PreparedStatement ps = conn.prepareStatement(insertSQL)
for(var poll in queue.poll()){
        ps.setBigDecimal(1, poll.getInAmount());
ps.addBatch();
}
            ps.executeBatch();

```
### Error log
```text
java.lang.IllegalArgumentException: BigDecimal(1362957524934568911617063559879000000000000.000000) should be between -100000000000000000000000000000000000000 and 100000000000000000000000000000000000000 exclusive of both values
	at com.clickhouse.data.ClickHouseChecker.newException(ClickHouseChecker.java:17)
	at com.clickhouse.data.ClickHouseChecker.between(ClickHouseChecker.java:183)
	at com.clickhouse.data.format.BinaryDataProcessor$Decimal128SerDe.serialize(BinaryDataProcessor.java:424)
	at com.clickhouse.data.ClickHouseDataProcessor.write(ClickHouseDataProcessor.java:593)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:350)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
```
#### Environment
* Client version: 0.6.0
* Language version: jdk17
* OS: windows11

#### ClickHouse server
* ClickHouse Server version: 23.8.2.7

**Comment by GaN601** [comment]
I forgot, the length of the integer should be 38-18. I apologize.
