### ISSUE TITLE
Caused by: java.sql.SQLException: <html> <head><title>405 Not Allowed</title></head>

### ISSUE THREAD

**Issue by z-one-one** [ClickHouse/clickhouse-java#1736]
1. when i update clickhouse-jdbc from ru.yandex.xxx to 0.6.0 ,it occured that :

clickhouse - Exception during pool initialization.

java.sql.SQLException:

<title>405 Not Allowed</title>

2. then i use a url to proxy clickhouse,but it still error that 

java.sql.SQLException: Unknown error 1002, server ClickHouseNode [uri=https://clickhouse.zxxxxxx.cn:443/default]@1629445028
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:131) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:335) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:288) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:157) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:41) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar!/:na]
Caused by: java.io.IOException: 
	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:184) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:227) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:124) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:1056) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:128) ~[clickhouse-jdbc-0.4.6.jar!/:clickhouse-jdbc 0.4.6 (revision: dd91e17)]
	... 80 common frames omitted

how could i resolve it ?please

**Comment by mzitnik** [comment]
From the stack trace looks like you are using `clickhouse-jdbc-0.4.6.jar`

**Comment by chernser** [comment]
Hi @z-one-one ! 
Would you please reproduce the issue with the latest client? 
Would you please describe you network between application and DB server? 
Thanks!

**Comment by chernser** [comment]
No answer.
