### ISSUE TITLE
Unexpected `BadSqlGrammarException` Instead of `TimeoutException` on Query Timeout

### ISSUE THREAD

**Issue by koyr-exem** [ClickHouse/clickhouse-java#1972]
### Describe the bug
When using the ClickHouse JDBC driver with JdbcTemplate in a Spring application, a query timeout is set using JdbcTemplate.setQueryTimeout(10). However, when the query exceeds the configured timeout, a BadSqlGrammarException is thrown instead of the expected TimeoutException. This behavior is misleading as it suggests an issue with SQL syntax rather than a timeout.

### Steps to reproduce
1. Configure JdbcTemplate with a query timeout: jdbcTemplate.setQueryTimeout(10) (10 seconds).
2. Execute a query that takes longer than the configured timeout.
3. Observe the exception thrown when the query times out.

### Expected behaviour
A TimeoutException or another appropriate exception should be thrown to clearly indicate that the query execution exceeded the configured timeout.

### Code example
```java
public executeQuery(String query) { 
        jdbcTemplate.query(query)
}
```
### Error log
```
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT * FROM large_table]; 
nested exception is java.sql.SQLException: Code: 159. DB::Exception: Timeout exceeded: elapsed 10.114165251 seconds, maximum: 10: While executing MergeTreeSelect(pool: ReadPoolInOrder, algorithm: InOrder). (TIMEOUT_EXCEEDED) (version 24.1.5.6 (official build))

	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:393)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:465)
```

#### Environment
* Client version: clickhouse-jdbc:0.4.6
* Language version: Java 11
* OS: windows 11

#### ClickHouse server
* ClickHouse Server version: 24.1.5.6
* ClickHouse Server non-default settings, if any:
* `CREATE TABLE` statements for tables involved:
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary

**Comment by chernser** [comment]
Good day, @koyr-exem ! 
Thank you for bringing it up. We will try to look into it soon.

**Comment by chernser** [comment]
Good day, @koyr-exem! 
Will be fixed in JDBC-v2. 
I would handle cause exception because Spring mapping doesn't cover all SQLState codes and will be off anyway.
