### ISSUE TITLE
[client-v2] Prevent using http client before it is initialized

### ISSUE THREAD

**Issue by chernser** [ClickHouse/clickhouse-java#2011]
### Describe the bug

Apache HTTP Client is used internally to make http calls. It take a time to initialize it but application may start doing requests. 
It will cause internal exception and exception is not recoverable. 

### Steps to reproduce
1. Create client
2. Immediately send some request 
3.

### Expected behavior
Request is executed successfully 

### Error log

```
com.clickhouse.client.api.ClientException: Failed to execute request
	at com.clickhouse.client.api.internal.HttpAPIClientHelper.executeRequest(HttpAPIClientHelper.java:385)
	at com.clickhouse.client.api.Client.lambda$insert$7(Client.java:1393)
	at com.clickhouse.client.api.Client.runAsyncOperation(Client.java:1942)
	at com.clickhouse.client.api.Client.insert(Client.java:1485)
	at 
...
Caused by: java.lang.IllegalStateException: Connection pool shut down
	at org.apache.hc.core5.util.Asserts.check(Asserts.java:38)
	at org.apache.hc.core5.pool.LaxConnPool.lease(LaxConnPool.java:163)
	at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.lease(PoolingHttpClientConnectionManager.java:298)
	at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.acquireEndpoint(InternalExecRuntime.java:103)
	at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:125)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
	at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
	at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
```

#### Environment
* Client version: 0.7.1

**Comment by chernser** [comment]
This issue happens only when client is used concurrently. 
We would need to add more detailed log.
