### ISSUE TITLE
Attempted read on closed stream.

### ISSUE THREAD

**Issue by akonyaev90** [ClickHouse/clickhouse-java#253]
```Caused by: java.sql.SQLException: java.io.IOException: Attempted read on closed stream.
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:129) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.ClickHouseResultSet.next(ClickHouseResultSet.java:143) ~[clickhouse-jdbc-0.1.42.jar:na]
	

Caused by: java.io.IOException: Attempted read on closed stream.
	at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:109) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:118) ~[httpclient-4.5.2.jar:4.5.2]
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.readNextBlock(ClickHouseLZ4Stream.java:82) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.checkNext(ClickHouseLZ4Stream.java:74) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.read(ClickHouseLZ4Stream.java:50) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.StreamSplitter.readFromStream(StreamSplitter.java:92) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.StreamSplitter.next(StreamSplitter.java:54) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:116) ~[clickhouse-jdbc-0.1.42.jar:na]
	... 70 common frames omitted

```

server version 18.12.14 revision 54407

I see this [ticket](https://github.com/yandex/clickhouse-jdbc/issues/175) was resolved, but I have same problems with driver.

**Comment by serebrserg** [comment]
Could you compose a test for the problem?
The basic case is covered with the test: https://github.com/yandex/clickhouse-jdbc/blob/master/src/test/java/ru/yandex/clickhouse/integration/ClickHouseStatementImplTest.java#L67

Is there concurrent access to the ResultSet?

**Comment by sourirer** [comment]
Don't close connection before you finish read data from ResultSet can avoid this issue.
