### ISSUE TITLE
setTimestamp  java.lang.NullPointerException

### ISSUE THREAD

**Issue by kuangye098** [ClickHouse/clickhouse-java#293]
JDBC version : 0.1.48 and JDK 1.8.171

```
      ClickHouseProperties properties = new ClickHouseProperties();
      properties.setUseServerTimeZone(false);
      ClickHouseProperties withCredentials = properties.withCredentials(this.username, this.password);
      this.clickHouseDataSource = new BalancedClickhouseDataSource(this.jdbcUrl, withCredentials);

      ```````
      ```````     
      ```````
      java.sql.Timestamp sqlTimestamp =  new java.sql.Timestamp(
                                1548042771L);
     preparedStatement.setTimestamp(columnIndex + 1, sqlTimestamp);
```
Caused by: java.lang.NullPointerException
        at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2342)
        at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2312)
        at java.util.Calendar.setTimeInMillis(Calendar.java:1804)
        at java.util.Calendar.setTime(Calendar.java:1770)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
        at java.text.DateFormat.format(DateFormat.java:345)
        at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.setTimestamp(ClickHousePreparedStatementImpl.java:247)
        at com.xx.datax.plugin.writer.clickhousewriter.CHWriter$Task.fillPreparedStatementColumnType(CHWriter.java:361)
        at com.xx.datax.plugin.writer.clickhousewriter.CHWriter$Task.fillPreparedStatement(CHWriter.java:272)
        at com.xx.datax.plugin.writer.clickhousewriter.CHWriter$Task.doBatchInsert(CHWriter.java:250)
        ... 5 more

**Comment by chernser** [comment]
No applicable for the new JDBC
