### ISSUE TITLE
Parse exception warning

### ISSUE THREAD

**Issue by alniks** [ClickHouse/clickhouse-java#652]
After upgrading to 0.2.6 I see the following warning in the log:

`Failed to parse the given SQL. If you believe the SQL is valid, please feel free to open an issue on Github with the following SQL and exception attached.
INSERT INTO events (uid, id, contact_id, type, email, user_id, latitude, longitude, ip, user_agent, url, merged_url, dsn_diag, vmta, dsn_status, log_source, host_name, domain_name, from_text, subject, time_logged, time_queued, bounce_category, dlv_destination_ip, dlv_source_ip, dsn_mta, browser, browser_version, platform, hardware, reply_to, amp, created_at, event_date) format TabSeparated 
8050ebf3-70ce-4956-a130-dea25d1bd4c9	228523	4643663	0	a2@a.a	207400	0	0										gmail.com														0	2021-05-06 09:38:10	2021-05-06
226658fb-b104-4f14-b143-2622cdb9513d	228523	4643663	1	a2@a.a	207400	0	0										gmail.com														0	2021-05-06 09:38:10	2021-05-06
417d54c5-c459-46ad-88be-b4e6f95d3bc7	228523	4643662	0	a1@a.a	207400	0	0										gmail.com														0	2021-05-06 09:38:10	2021-05-06
d4ec4b0a-3bca-473c-88af-a6cef6fb74b8	228523	4643662	1	a1@a.a	207400	0	0										gmail.com														0	2021-05-06 09:38:10	2021-05-06
1f08a165-ae70-472c-b769-ab9b00a24e11	228523	4643664	0	a3@a.a	207400	0	0										gmail.com														0	2021-05-06 09:38:10	2021-05-06
8de41622-8a04-4325-94f3-52120c35fbb7	228523	4643664	1	a3@a.a	207400	0	0										yahoo.com														0	2021-05-06 09:38:10	2021-05-06
129b84b2-2c02-4e68-bce2-49a836d14ce2	228524	4643663	0	a2@a.a	207400	0	0										yahoo.com														0	2021-05-06 09:38:10	2021-05-06
68c5c599-1461-4c0c-ae99-686f74de631d	228524	4643663	1	a2@a.a	207400	0	0										yahoo.com														0	2021-05-06 09:38:10	2021-05-06
9db49e72-f60b-472a-b704-3fb48dd87729	228524	4643662	0	a1@a.a	207400	0	0										yahoo.com														0	2021-05-06 09:38:10	2021-05-06
f9bd398f-0a70-4cbe-a4f7-2f1bdaebd81e	228524	4643662	1	a1@a.a	207400	0	0										yahoo.com														0	2021-05-06 09:38:10	2021-05-06
1fb86d2e-89a8-4c46-a933-259108bf96ea	228525	4643665	0	a1@a.a	207402	0	0										yahoo.com														0	2021-05-05 09:38:10	2021-05-05
10d8b218-04b2-426e-9c52-6009c0247f47	228525	4643665	1	a1@a.a	207402	0	0										yahoo.com														0	2021-05-05 09:38:10	2021-05-05
41ccf75a-47ad-4a11-8387-7d9f3b548b6a	228525	4643665	0	a1@a.a	207402	0	0										yahoo.com														0	2021-05-05 09:38:10	2021-05-05
c8e59845-35de-47b9-9cac-5df49882bd88	228525	4643665	1	a1@a.a	207402	0	0										yahoo.com														0	2021-05-05 09:38:10	2021-05-05
41babce9-c8b3-422d-992d-676ef15be907	228525	4643665	2	a1@a.a	207402	1.0	1.0	ip	{\"raw_user_agent\":\"agent\",\"dev\":null,\"os\":null}								yahoo.com														0	2021-05-06 09:38:10	2021-05-06
2ecb15d7-f13d-4ba1-bc87-a4cb14c4f938	228525	4643665	2	a1@a.a	207402	1.0	1.0	ip	{\"raw_user_agent\":\"agent\",\"dev\":null,\"os\":null}								yahoo.com														0	2021-05-06 09:38:10	2021-05-06
6ecadc90-470e-4c0b-a413-c630066cc847	228523	4643663	2	a2@a.a	207400	1.0	1.0	ip	{\"raw_user_agent\":\"agent\",\"dev\":null,\"os\":null}								yahoo.com														0	2021-05-06 09:38:10	2021-05-06
78132388-8b96-4ddd-b52f-3a899b770c6c	228523	4643664	7	a3@a.a	207400	0	0					smtp;450 Service temporarily unavailable. Please see http://www.mail-abuse.com/cgi-bin/lookup					yahoo.com														0	2021-05-06 09:38:10	2021-05-06
db0e62be-68d3-451d-922d-c26a95318756	228524	4643663	2	a2@a.a	207400	1.0	1.0	ip	{\"raw_user_agent\":\"agent\",\"dev\":null,\"os\":null}								yahoo.com														0	2021-05-06 09:38:10	2021-05-06`

Stacktrace:

`ru.yandex.clickhouse.jdbc.parser.ParseException: Parse error at line 19, column 82.  Encountered: 450\r
	at ru.yandex.clickhouse.jdbc.parser.ClickHouseSqlParser.generateParseException(ClickHouseSqlParser.java:8935)\r
	at ru.yandex.clickhouse.jdbc.parser.ClickHouseSqlParser.jj_consume_token(ClickHouseSqlParser.java:8870)\r
	at ru.yandex.clickhouse.jdbc.parser.ClickHouseSqlParser.sql(ClickHouseSqlParser.java:159)\r
	at ru.yandex.clickhouse.jdbc.parser.ClickHouseSqlParser.parse(ClickHouseSqlParser.java:100)\r
	at ru.yandex.clickhouse.jdbc.parser.ClickHouseSqlParser.parse(ClickHouseSqlParser.java:83)\r
	at ru.yandex.clickhouse.ClickHouseStatementImpl.parseSingleStatement(ClickHouseStatementImpl.java:109)\r
	at ru.yandex.clickhouse.ClickHouseStatementImpl.parseSingleStatement(ClickHouseStatementImpl.java:127)\r
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeUpdate(ClickHouseStatementImpl.java:312)\r
	at org.javalite.activejdbc.DB.exec(DB.java:624)\r
	at test.helpers.TestHelper.createClickHouseEvents(TestHelper.java:444)\r
	at app.services.analytics.DashboardServiceSpec.createEvents(DashboardServiceSpec.java:181)\r
	at app.services.analytics.DashboardServiceSpec.setUp(DashboardServiceSpec.java:60)\r
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)\r
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)\r
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\r
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\r
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\r
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)\r
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\r
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\r
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\r
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\r
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\r
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)\r
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)\r
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:39)\r
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)\r
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)\r
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)\r
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)\r
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)\r
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)\r
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)\r
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)\r
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)\r
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)\r
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:79)\r
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:70)\r
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)\r
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)\r
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)\r
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)\r
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)\r
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)\r
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)\r
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)\r
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)\r
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)\r
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)\r`

**Comment by zhicwu** [comment]
Sorry it didn't work for you. Is there a line-break after `format TabSeparated`?

**Comment by zhicwu** [comment]
I see what's going on. The parsing should be stopped when it's an insert statement using specific input format.

**Comment by alniks** [comment]
Yes, I have the line break

**Comment by chernser** [comment]
Closing as not enough information. 
And not applicable for JDBC-v2
